### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by robksawyer** [driftyco/ionic-platform-web-client#10]
I keep getting the following and I'm using the latest from master.

The following is inside of my `bower.json`.
`"ionic-platform-web-client": "https://github.com/driftyco/ionic-platform-web-client.git#master"`

```
Uncaught TypeError: Cannot read property 'get' of undefined
get @ ionic.io.bundle.js:3426
get @ ionic.io.bundle.js:3460
Settings @ ionic.io.bundle.js:3451
21.../push/push-token @ ionic.io.bundle.js:3673
s @ ionic.io.bundle.js:1
e @ ionic.io.bundle.js:1
(anonymous function) @ ionic.io.bundle.js:1
```

**Comment by ivanarrizabalaga** [comment]
+1

**Comment by ivanarrizabalaga** [comment]
I found the solution for me.
After updating dependencies via **bower update** you have to do **ionic io init** again in order to set the current settings for your services.

**Comment by robksawyer** [comment]
@ivanarrizabalaga that worked great! Thanks! Any idea about what might be happening at <https://github.com/driftyco/ionic/issues/4498>?

**Comment by ericb** [comment]
@robksawyer @ivanarrizabalaga As an alternative, you can run `ionic config build` which should have the same affect. Running `io init` isn't harmful, but it's a bit misleading as that just happens to be running config build under the hood.

**Comment by petruisfan** [comment]
Still having this issue...
```
ionic.io.bundle.js:3432 Uncaught TypeError: Cannot read property 'get' of undefined
```

**Comment by rapheki** [comment]
@petruisfan I found the answer to this problem here https://github.com/driftyco/ionic-platform-web-client/issues/4 (I'm using a custom app structure & a custom gulpfile)

**Comment by gauravsaini03** [comment]
@ericb I am not using any custom app structure, also I build "ionic config build" but still getting error of 'get' of undefined

I am trying installing ionic-platform-web-client with below steps
1. create fresh new starter project
2. ionic add ionic-platform-web-client
3. ionic io init
4. ionic config build

Although, after this it should automatically add script and dependencies in app.js for ionic-platform-web-client but it didn't. (as I am installing fresh without any custom directory)

After that, I added script tag in index.html and dependencies in app.js

but still getting error in ionic.io.bundle
Uncaught TypeError: Cannot read property 'get' of undefined

**Comment by ericb** [comment]
@gauravsaini03 Have you updated to the latest ionic CLI? The latest as of writing this is 1.7.10

**Comment by gauravsaini03** [comment]
I am using 1.6.4, but in docs its mentioned that it should be greater than 1.6 

Although, I quickly tested in my friend's laptop which have 1.7.10 version and it worked perfectly :)

**Comment by ericb** [comment]
@gauravsaini03 Do you know where it mentions that in the docs? That was for a previous iteration of the config. We've since provided another update that requires a newer version and I'll gladly update the docs if you happen to know where it mentioned it.

**Comment by gauravsaini03** [comment]
@ericb In the docs at http://docs.ionic.io/docs/io-config
I saw this line in troubleshooting "You'll need to upgrade your CLI version to at least version 1.6.2"

**Comment by ericb** [comment]
@gauravsaini03 Thanks. I've updated that reference.
