### ISSUE TITLE
Ionic 2 support

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic-platform-web-client#100]
Could we have some updates on this please? :)

**Comment by dwieeb** [comment]
You can follow progress here: https://github.com/driftyco/ionic-platform-web-client/pull/84

Obviously we haven't provided an update in some time, so I'll give one. We've put the Ionic 2 support for the platform client on hold just for a short while as we tackle some higher priority issues, one of which being the Beta Deprecation email that was sent out just today. Hopefully in the coming week we'll have time to finish our testing and get the branch merged in and have a release out.

**Comment by Manduro** [comment]
Thanks, forgot to check the PR's for info!

**Comment by matheo** [comment]
Im looking forward too, as i'm getting the same error of #81 trying to use Ionic 2 + TypeScript
