### ISSUE TITLE
ion-track-tap does not work on ion-tab

### ISSUE THREAD

**Issue by jclalala** [driftyco/ionic-platform-web-client#101]
There are no analytics events issued when tabs are clicked, here's a code snippet:

```
<ion-tab title="{{ 'TABS.MYSESSION' | translate }}" icon-off="ion-ios-chatboxes-outline" icon-on="ion-ios-chatboxes"
           href="#/tab/listTutorSession" ng-if="currentUser.userType == userType.tutor"
           ion-track-tap="click tab listTutorSession">
    <ion-nav-view name="tab-listTutorSession"></ion-nav-view>
  </ion-tab>
```

clicking on the tab icon does not issue the "click tab listTutorSession" event from console. Other events (e.g. on buttons) work just fine.

**Comment by dwieeb** [comment]
@jclalala We have deprecated `ionic-platform-web-client` and we're looking to implement a new analytics solution for the [Cloud Client](https://github.com/driftyco/ionic-cloud). Keep an eye on our blog for analytics support in Ionic 1 & 2.
