### ISSUE TITLE
ionic-platform-web-client preventing data restore

### ISSUE THREAD

**Issue by jessica-azgs** [driftyco/ionic-platform-web-client#102]
Something in this package is preventing the software I use to backup my app data from restoring  these data backups. I don't really know enough to debug this further so I apologize about my lack of information regarding this issue.

I use [iMazing](https://imazing.com/) to create the data backups for my app. These backups were working fine until I installed the ionic-platform-web-client. I was testing out using Ionic Platform to build my apps instead of PhoneGap Build. The build of the app went fine though there was an issue using Deploy to update on iOS but I think you guys may have fixed this by now. 

After adding ionic-platform-web-client iMazing could no longer restore new or old app data whether I built the app with Ionic Platform or with PhoneGap Build. There was no error, the data just wasn't restored. However, once I removed ionic-platform-web-client (and that was all I removed) restoring backedup data worked fine again with the app built with PhoneGap Build.

In the [iMazing docs](https://imazing.com/imazing-1-3-app-back-uprestore) I see that data backups "are compatible with the vast majority of apps, with 2 exceptions:

1. Apps which do not restore state exhaustively when doing a full restore of a backup ( developer error or choice )
1. Apps which store user data in a shared container ( WhatsApp for example ) – we do hope to support these very soon."

I don't know if adding ionic-platform-web-client makes either of these true or what exactly is changing when ionic-platform-web-client is added that makes iMazing unable to restore data backups.

My environment and plugins

```
Windows 7
ionic cli 1.7.14
ionic 1.2.4
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-sqlite-storage 0.7.14 "Cordova sqlite storage plugin"
ionic-plugin-deploy 0.5.0 "IonicDeploy"
ionic-plugin-keyboard 2.0.1 "Keyboard"
```

**Comment by ericb** [comment]
Hrm, while I'm not going to rule this out 100%, i'm 99.9% sure that this would not be caused via the platform client. It's purely a javascript library that sits in the www/lib directory. I would think it more likely that there is a conflicting library used in one of the plugins you have installed (deploy uses a zip lib that has been known to conflict with other plugins using the same one, so that might be a good place to start).

I'm going to close this for now, feel free to reopen if you can narrow down something with this library directly.
