### ISSUE TITLE
Mock ionic.io services

### ISSUE THREAD

**Issue by astik** [driftyco/ionic-platform-web-client#105]
It would be great to have a way to mock ionic.io angular service ($ionicAuth, $ionicUser, $ionicDeploy) like we do with $http and $httpBackend. Even simple configurable decorator would be perfect =)
On a longer shot, we may also dream of a $ionicPush mock that would use a dummy backend that can simulate sending push notification.

**Comment by dwieeb** [comment]
@astik @vdelacou I'd like to continue discussing this in the new Cloud Client repo, if you don't mind: https://github.com/driftyco/ionic-cloud/issues/7
