### ISSUE TITLE
always got "Uncaught TypeError: Cannot read property 'on' of undefined" when dev_push is false

### ISSUE THREAD

**Issue by zjx** [driftyco/ionic-platform-web-client#106]
i am using ionic push feature based on the full setup guide, when using dev_push everything is ok. Anyway right after i run the command "ionic config set dev_push false" then the ionic push plugin will prompt an error when the app starts up.  The error looks like below:

I/chromium: [INFO:CONSOLE(2)] "Ionic Push:", source: file:///android_asset/www/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js (2)
I/chromium: [INFO:CONSOLE(2)] "Ionic Push:", source: file:///android_asset/www/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js (2)
I/chromium: [INFO:CONSOLE(3)] "Uncaught TypeError: Cannot read property 'on' of undefined", source: file:///android_asset/www/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js (3)

**Comment by ericb** [comment]
Sounds like maybe you've forgotten to install the push plugin or it is not available in the build. Try removing and adding the plugin again if you've previously installed it.

**Comment by zjx** [comment]
@ericb, actually the push plugin already there. i can see the adobe.phonegap.push package and all of the classes related to gcm and push plugin. 
do you mean i need to uninstall & reinstall the phonegap-push-plugin separately? i used the ionic add ionic-platform-web-client command.

**Comment by zjx** [comment]
here is the error code snippet, this error occurred on self._emitter.on() statement.

    key: "onReady",
    value: function onReady(callback) {
      var self = this;
      if (this._isReady) {
        callback(self);
      } else {
        console.log(self);
        console.log(self._emitter);
        self._emitter.on('ionic_push:ready', function () {
          callback(self);
        });
      }
    }

**Comment by zjx** [comment]
ionic plugin list
android-plugin-imosandnative true "android-plugin-imosandnative"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
cordova-sqlite-storage 1.2.1 "Cordova sqlite storage plugin (core version)"
ionic-plugin-keyboard 2.0.1 "Keyboard"
phonegap-plugin-push 1.6.3 "PushPlugin"

**Comment by zjx** [comment]
finally found if use phonegap-push-plugin, then everything works fine..

You should not use Ionic.push() in the app.js.. workable code should be something like:

var push = PushNotification.init({

....

**Comment by ericb** [comment]
Sorry for the delay. @zjx You should not need to use the push plugin directly. If it's erroring on the _emitter portion, you likely have an outdated version of the ionic-platform-web-client. It could also be that you're missing the GCM key if you haven't set it in your config (or perhaps you need to run an ionic config build).

**Comment by andreimarinescu** [comment]
For what it's worth, I'm having the same issue. I've checked and I'm running the 1.6.3 version of phonegap-plugin-push, and I don't have any direct dependencies on the ionic-platform-web-client.

**Comment by andreimarinescu** [comment]
So at least in my case, I needed to run ionic config set gcm_key <SENDER_ID>. That fixes the issue, however a log message letting me know what's missing would have been nice (I guess I need to post this to the plugin-push github page though). Just posting this here in case anyone else faces this.

**Comment by JMoli** [comment]
I recently enabled push and  removed dev on a fresh app. I followed the version 2 ionic docs IN ORDER, and had no problems.
