### ISSUE TITLE
ionic.auth change password 

### ISSUE THREAD

**Issue by Boxnia** [driftyco/ionic-platform-web-client#107]
How I can change the password?

I register my users with:

Ionic.Auth.signup(details).then(signupSuccess, signupFailure);

I login my users with:

Ionic.Auth.login(authProvider, authSettings, loginDetails)
.then(authSuccess, authFailure);

I tried with:

user.set('password', xxxxx);

and,

user.resetPassword();

but This, send email with a new password, but I want to change  password that 
user chooses.

Any idea?

**Comment by Fuiste** [comment]
Check out the user's `details` field ([docs](http://docs.ionic.io/docs/user-usage#section-user-details)).  You can use this in conjunction with `resetPassword` to allow users to change their password.

**Comment by Boxnia** [comment]
ok, it's work.

with resetPassword, I receive the message with the new password and I can signin, but I want to change the password, customize, I can change the password and I put you want.

but I don't know how to do it

**Comment by Boxnia** [comment]
I tried with:

var user = Ionic.User.current();
          user.set(user.details.password, $scope.modifypass.password2)
        user.save();

but don't work....
