### ISSUE TITLE
onic Deploy: no updates available

### ISSUE THREAD

**Issue by hossam9995** [driftyco/ionic-platform-web-client#111]
hello,

I'am using ionic deploy plugin and i do every thing on this doc http://docs.ionic.io/docs/deploy-quick-start

but its always return for me Ionic Deploy: no updates available

i use the version and info function to return some information

**check update function return all time**
`onic Deploy: no updates available`

**version function return **
`Array[0]length: 0__proto__: Array[0]
`
**info function return**
`Object binary_version: "0.0.1"deploy_uuid: "NO_DEPLOY_AVAILABLE"__proto__: Object `
what i should to do to defined the uuid ?

hint i use ionic 1 and i use cutsom strucure 
see the strucre https://github.com/diegonetto/generator-ionic

thanks alot

**Comment by ericb** [comment]
closing due to duplicate driftyco/ionic-plugin-deploy/issues/69
