### ISSUE TITLE
Push: wrong senderID

### ISSUE THREAD

**Issue by rkreienbuehl** [driftyco/ionic-platform-web-client#113]
I set up an app with push. When I tried it on iOS all work fine. On Android it doesn't work with the folowing console logs:
`13    145038   log      Ionic Push:, register
15    146189   error    Ionic Push:, (debug) unexpected error occured.
16    146189   error    Ionic Push:, [object Object]`
After a long time of searching I found out, that instead of the senderID I set in the package.json always the GCM_Key was used as senderID.

I found the code in the ionic.io.bundle.min.js:
`e.pluginConfig.android.senderID=t.app.gcmKey`
After I inserted the senderID right there all worked fine.

**Comment by ericb** [comment]
Yup, the push plugin recently started grabbing the "sender id" during installation, but it still uses the gcm key we provide it (they are the same thing, just different names). I believe the plugin will eventually switch to using the sender id that you give during installation, but as far as i know, it currently just uses the gcm key passed by us.
