### ISSUE TITLE
All notification enqueued and not received - Proper push usage

### ISSUE THREAD

**Issue by clement360** [driftyco/ionic-platform-web-client#114]
I want to verify that I am using the service in a safe way. I have a mysql db running on aws, whenever a new account is created I run push.register and add the token up to the server and add it to the user in the db. Whenever I need to notify that user I get their token from the users table and send the notification using the API. Is this bad form? also ever since I set dev_push false all my notifications send but are permanently enqueued.

`{
  "data": {
    "state": "enqueued",
    "app_id": "b330aa42",
    "status": "locked",
    "uuid": "1a97e8b7-5083-4d34-9729-d06f8c820d7a",
    "config": {
      "notification": {
        "title": "Hi",
        "ios": {
          "title": "Howdy",
          "message": "Hello iOS!"
        },
        "android": {
          "title": "Hey",
          "message": "Hello Android!"
        },
        "message": "Hello world!"
      },
      "profile": "fake_push_profile",
      "tokens": [
        "feLuLgKQ6Uk:APA91bGt_DYsoSM-gChOOUfH44u_FV3DBFYzfK5uNfb1iJODG2iZqcBY9y9esqquvixB2ZmmzYQzwCv9ktPoqmU1AW5Xn3Wc6cmd4zOCf9XwJBiqA1BB_OF9A5qJcnPOP5gkmClBddvc"
      ]
    },
    "created": "2016-05-23T20:44:44.164749+00:00"
  },
  "meta": {
    "status": 200,
    "request_id": "f7a5c259-2b63-4ead-9134-640ec73d48eb",
    "version": "2.0.0-beta.0"
  }
}`

**Comment by Fuiste** [comment]
`enqueued` is a status for the notification, not the individual messages which reflect delivery or lack thereof (check out the docs [here](http://docs.ionic.io/docs/push-sending-push#section-notifications-vs-messages) and a reference [here](http://docs.ionic.io/docs/push-sending-push#responses)).

To see the delivery status of your messages, check out [this](http://docs.ionic.io/docs/push-sending-push#section-checking-the-status-of-a-push) example and view the error code reference [here](http://docs.ionic.io/v2.0.0-beta/docs/push-error-codes).

**Comment by clement360** [comment]
Turns out, my gcm was set up using the IP of my aws server. I re did it using a blank IP and it worked

**Comment by clement360** [comment]
But it's my usage correct? I don't need to call the register command every time the app opens? And if I do will the tokens change on me!?

**Comment by Fuiste** [comment]
You should be calling register on each start of the app, yes.

Re-registering will not generate a different token under normal operation.

**Comment by clement360** [comment]
Thanks!

**Comment by ovoshlook** [comment]
Hi. Sending push throug service. Status ENQUEUED but notification not received.
TRying to check status of my message.
It gives me strange response
{"meta": {"status": 200, "version": "2.0.0-beta.0", "request_id": "8fd9abd0-0312-4354-a8de-ad8a4a436e1e"}, "data": []}

it is 200 but emty
