### ISSUE TITLE
Running function when notification is received and application backgrounded/suspended

### ISSUE THREAD

**Issue by clement360** [driftyco/ionic-platform-web-client#115]
following this: http://docs.ionic.io/docs/push-sending-push#section-sending-background-notifications

I'm sending the example json and onNotification is being run as long as the application is open. however  whenever I leave the app and send the same notification my breakpoint is never hit. How can I have the application run onNotification when it is not open?

**Comment by Fuiste** [comment]
Will your `onNotification` run when the app is started up again?

**Comment by clement360** [comment]
it does not run on re-opening. however logcat shows this: 


05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: onMessage - from: 513436981549
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: normalize extras
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: key = payload
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: replace key payload with payload
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: key = gcm.notification.content_available
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: replace key gcm.notification.content_available with content_available
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: key = content_available
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: replace key content_available with content_available
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: key = collapse_key
05-24 17:06:20.074 10980 11327 D PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
05-24 17:06:20.075 10980 11327 D PushPlugin_GCMIntentService: background
05-24 17:06:20.075 10980 11327 D PushPlugin_GCMIntentService: message =[null]
05-24 17:06:20.075 10980 11327 D PushPlugin_GCMIntentService: title =[null]
05-24 17:06:20.075 10980 11327 D PushPlugin_GCMIntentService: contentAvailable =[null]
05-24 17:06:20.261  3223  3366 I Vision  : Attempting to open download_details.json in com.google.android.gms.vision
05-24 17:06:20.262  3223  3366 W Vision  : Failed to open download_details.json in com.google.android.gms.vision: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms.vision
05-24 17:06:20.262  3223  3366 I Vision  : Attempting to open download_details.json in com.google.android.gms.policy_ccocr_vision
05-24 17:06:20.269  3223  3366 W Vision  : Failed to open download_details.json in com.google.android.gms.policy_ccocr_vision: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms.policy_ccocr_vision
05-24 17:06:20.269  3223  3366 W Vision  : Reading download details from hard-coded Java

**Comment by clement360** [comment]
when the app is open logcat shows this:

05-24 17:05:57.492 10980 11297 D PushPlugin_GCMIntentService: onMessage - from: 513436981549
05-24 17:05:57.492 10980 11297 D PushPlugin_GCMIntentService: normalize extras
05-24 17:05:57.492 10980 11297 D PushPlugin_GCMIntentService: key = payload
05-24 17:05:57.492 10980 11297 D PushPlugin_GCMIntentService: replace key payload with payload
05-24 17:05:57.492 10980 11297 D PushPlugin_GCMIntentService: key = gcm.notification.content_available
05-24 17:05:57.492 10980 11297 D PushPlugin_GCMIntentService: replace key gcm.notification.content_available with content_available
05-24 17:05:57.492 10980 11297 D PushPlugin_GCMIntentService: key = content_available
05-24 17:05:57.492 10980 11297 D PushPlugin_GCMIntentService: replace key content_available with content_available
05-24 17:05:57.493 10980 11297 D PushPlugin_GCMIntentService: key = collapse_key
05-24 17:05:57.493 10980 11297 D PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
05-24 17:05:57.493 10980 11297 D PushPlugin_GCMIntentService: foreground
05-24 17:05:57.493 10980 11297 D PushPlugin: convert extras to json
05-24 17:05:57.493 10980 11297 D PushPlugin: key = payload
05-24 17:05:57.493 10980 11297 D PushPlugin: key = content_available
05-24 17:05:57.493 10980 11297 D PushPlugin: key = collapse_key
05-24 17:05:57.493 10980 11297 D PushPlugin: key = foreground
05-24 17:05:57.493 10980 11297 V PushPlugin: extrasToJSON: {"additionalData":{"payload":{"foo":"bar"},"content_available":"1","collapse_key":"do_not_collapse","foreground":true}}
05-24 17:05:57.615   917   926 I art     : Background partial concurrent mark sweep GC freed 112671(6MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 41MB/57MB, paused 1.068ms total 193.928ms
05-24 17:05:58.209   917  3298 D NetlinkSocketObserver: NeighborEvent{elapsedMs=14998685, 192.168.1.1, [20E52A2C41EA], RTM_NEWNEIGH, NUD_STALE}

The only difference I see is the following only shows up when the app is open:

convert extras to json
05-24 17:05:57.493 10980 11297 D PushPlugin: key = payload
05-24 17:05:57.493 10980 11297 D PushPlugin: key = content_available
05-24 17:05:57.493 10980 11297 D PushPlugin: key = collapse_key
05-24 17:05:57.493 10980 11297 D PushPlugin: key = foreground
05-24 17:05:57.493 10980 11297 V PushPlugin: extrasToJSON: {"additionalData":{"payload":{"foo":"bar"},"content_available":"1","collapse_key":"do_not_collapse","foreground":true}}

**Comment by clement360** [comment]
@Fuiste Any suggestions? I've been digging into docs and trying a ton of different JSON payloads using content_available and content-available. This is kind of a crucial part of my application

**Comment by clement360** [comment]
the docs are incorrect, you must use "content-available": 1 no underscore also the notification needs a message. please update the docs. I spent far too much time on this

"notification": {
        "payload": {
            "notificationType": "5555"
        },
        "android": {
            "data": {
                "title": "",
                "message": "",
                "content-available": 1
            }
        },
        "ios": {
            "content_available": 1
        }
    }

**Comment by clement360** [comment]
also I have no idea if this works on ios I was only able to test android

**Comment by Fuiste** [comment]
`content-available` is only supported within the `data` key as that is passed directly through to the plugin, and thus does not follow Ionic's schema.    Ionic's `content_available` should have the same effect outside the `data` key, but it is not a 1-to-1 mapping as it is our own schema and follows the pattern laid out in the docs.

Finally, this is sort of beside the point, as the GCM flag `content-available` will only affect iOS pushes delivered through GCM, which are not used by Ionic (we send directly through APNS).  The payload you specified above (using the `data` key) would work with or without `content-available`.
