### ISSUE TITLE
Ionic v2

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic-platform-web-client#119]
Is it possible to use Ionic IO with Ionic 2 applications? I didn't found any resource online that would describe the process of integrationg Ionic IO into Ionic 2 apps.

**Comment by Kobzol** [comment]
Sorry, I finally found it (https://www.npmjs.com/package/@ionic/platform-client-angular for others). I didn't realize that there is a V2 branch on this repo.

**Comment by dwieeb** [comment]
We hope to officially release v2 support next week.
