### ISSUE TITLE
Update web client to support new phonegap-plugin-push changes

### ISSUE THREAD

**Issue by aaabidunique** [driftyco/ionic-platform-web-client#122]
Please update and add support for new changes that are present in phonegap-plugin-push like clearAllNotifications  and  setApplicationIconBadgeNumber present in phonegap-plugin-push version 1.7.1.

**Comment by ericb** [comment]
The plugin is available directly with `getPushPlugin()`. You can utilize any plugin specific actions directly with the plugin.
