### ISSUE TITLE
Help me Please !

### ISSUE THREAD

**Issue by chawanith** [driftyco/ionic-platform-web-client#123]
![1](https://cloud.githubusercontent.com/assets/13082831/16344160/6bf266a4-3a65-11e6-9daf-158920c49c11.PNG)

**Comment by Fuiste** [comment]
There may be a version conflict happening under the hood.  Ensure that _no_ version of the `ionic-platform-web-client` is installed on your machine first.

You can also try installing the platform web client using `bower`, though this will require you to manually include the bundle in your `index.html` and inject it in your `app.js`

**Comment by dwieeb** [comment]
Try clearing the bower cache, too.
