### ISSUE TITLE
push.unregister() fails with HTTP 422 (UNPROCESSABLE ENTITY)

### ISSUE THREAD

**Issue by tomazberisa** [driftyco/ionic-platform-web-client#124]
After a successful ```push.register()``` upon login, our app does a ```push.unregister()``` upon logout.

```push.unregister()``` seems to transmit a ```POST``` to ```https://api.ionic.io/push/tokens/invalidate```, which results in a HTTP 422 (UNPROCESSABLE ENTITY) with the following ```'body'```:

```
error: {type: "UnprocessableEntity", link: null, message: "app_id not specified"}
meta: {version: "2.0.0-beta.0", request_id: "b3fc5286-737a-4c89-8f52-02e09f35d720", status: 422}
```

Build info:

```
$ ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.4
ios-sim version: 5.0.3
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.3 Build version 7D175

```

**Comment by tomazberisa** [comment]
This points towards lines 267-270 of ```ionic-platform-web-client/src/push/push.js``` (i.e., lines 5889-5892 of ```ionic-platform-web-client/dist/ionic.io.bundle.js```). The problem is partially remedied after changing:

```
'json': {
  'platform': platform,
  'token': self.getStorageToken().token
}
```
to
```
'json': {
  'app_id': settings.get('app_id'),
  'platform': platform,
  'token': self.getStorageToken().token
}
```

This in turn causes in a successful HTTP 204 NO CONTENT response, but causes a ```SyntaxError: JSON Parse error: Unexpected EOF``` in line 291 of ```ionic-platform-web-client/dist/ionic.io.bundle.js```. The cause of this is the backend returning an empty response, which is not valid JSON (i.e., ```''``` is not valid JSON, while ```'""'``` is valid). I see 2 potential solutions:

1. API provides a properly formatted JSON response
2. Take into account the 204 NO CONTENT response and use it override JSON parsing, since there is no content, i.e., adjust lines 289-293 from:

```
xhr.body = xhr.responseText
if(options.json) {
  try        { xhr.body = JSON.parse(xhr.responseText) }
  catch (er) { return options.callback(er, xhr)        }
}
```
to
```
xhr.body = xhr.responseText
if(options.json && xhr.status!=204) {
  try        { xhr.body = JSON.parse(xhr.responseText) }
  catch (er) { return options.callback(er, xhr)        }
}
```

**Comment by dwieeb** [comment]
@tomazberisa This issue was addressed in the new [Cloud Client](https://github.com/driftyco/ionic-cloud). (In beta).

In the new version we moved away from `browser-request`, which was causing the 204 issue. A 204 is a valid response and is expected to not have an HTTP body. `browser-request` was just wrong. 

We also always send the `app_id` to the endpoint, which fixes the 422 issue.

 Thanks for the descriptive write-up!

**Comment by tomazberisa** [comment]
Got it, thanks!

We saw the Cloud Client repo, but weren't able to find any documentation on how to use it - did we miss it somewhere or should we wait for it to come out of beta?

**Comment by dwieeb** [comment]
The best resources right now would be the [README](https://github.com/driftyco/ionic-cloud#readme) and the [Migration Guide](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide). We're working on some proper documentation now, but the Cloud Client is still quite volatile and there will be some breaking changes. Everything should be cleared up in the next couple weeks.

**Comment by dwieeb** [comment]
If you get it working or find some issues with it, please give some feedback! I made an issue for feedback here: https://github.com/driftyco/ionic-cloud/issues/3

**Comment by barhoumsec1122** [comment]
Hello , i have an error in my post request for sending push notification with error code 422 when  I try 
to invoke the service from javascript  but the  json request  wos correct :


{
	"method": "POST",
	"url": "https://api.ionic.io/push/notifications",
	"headers": {
		"Content-Type": "application/json",
		"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTIxY2Y0MS0zMjMyLTQ5ZGYtOTNmZC02MzRjZmEzN2JmYTAifQ._sh6VMYYU2pdiWzRBVnkqlYr5-FDwb-1bNUNrWkfeD0"
	},
	"data": {
		"tokens": ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkN2M1ZGNhOS0zMjA2LTQ1YjQtYTM2Ny1kMDVlYzdhMmY3MGEifQ.TSGxJIozInXYd9vJ2FpdjMbNJ8ZGadVyZB-KVoP2gK4"],
		"profile": "feelings-security",
		"notification": {
			"title": "Hi",
			"message": "Vous n'avez pas effectuer votre feelings du mois!",
			"android": {
				"title": "Hey",
				"message": "Hello Android!"
			},
			"ios": {
				"title": "Howdy",
				"message": "Vous n 'avez pas effectuer votre feeling du mois de mars "
			}
		}
	}
}


and the respanse wss 


{
	"meta": {
		"status": 422,
		"version": "2.0.0-beta.0",
		"request_id": "400eb772-ba00-4a21-cad6-23a77ed4d80b"
	},
	"error": {
		"link": null,
		"type": "UnprocessableEntity",
		"message": "An error occurred while validating the request parameters.",
		"details": [{
			"parameter": "profile",
			"errors": ["Profile tag can only contain lowercase characters and underscores, with no spaces."],
			"error_type": "invalid"
		}]
	}
}


and the code wos 



    sendPushNotification = function () {
           //init http headers

           $http.defaults.headers.put['Content-Type'] = 'application/json';
           $http.defaults.headers.post['Content-Type'] =  'application/json';


            var jwt = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTIxY2Y0MS0zMjMyLTQ5ZGYtOTNmZC02MzRjZmEzN2JmYTAifQ._sh6VMYYU2pdiWzRBVnkqlYr5-FDwb-1bNUNrWkfeD0';                      // server  token API
            var tokens = ['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkN2M1ZGNhOS0zMjA2LTQ1YjQtYTM2Ny1kMDVlYzdhMmY3MGEifQ.TSGxJIozInXYd9vJ2FpdjMbNJ8ZGadVyZB-KVoP2gK4'];                 // target token
            var profile = 'feelings-security';

                // Build the request object
                var req = {
                  method: 'POST',
                  url: 'https://api.ionic.io/push/notifications',
                  headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Bearer ' + jwt
                  },
                  data: {
                    "tokens": tokens,
                    "profile": profile,
                    "notification": {
                      "title": "Hi",
                      "message": "Vous n'avez pas effectuer votre feelings du mois!",
                      "android": {
                        "title": "Hey",
                        "message": "Hello Android!"
                      },
                      "ios": {
                        "title": "Howdy",
                        "message": "Vous n 'avez pas effectuer votre feeling du mois de mars "
                      }
                    }
                  }
                };

                  console.log("JSON request est :", JSON.stringify(req));
                // Make the API call
                $http(req).success(function(resp){
                  // Handle success
                  console.log("Ionic Push: Push success", JSON.stringify(resp));
                }).error(function(error){
                  // Handle error
                  console.log("Ionic Push: Push error", JSON.stringify(error));
                });
        };

 
Any Help  my friends ?

**Comment by gscardovelli** [comment]
@barhoumsec1122 Your response errors states "Profile tag can **only contain lowercase characters and underscores**, with no spaces.", so your profile tag "feelings-security" does not fit. Create another profile and name it accordingly (for example "feelingssecurity").
This did work form me.
