### ISSUE TITLE
Error: Variable(s) missing (use: --variable SENDER_ID=value).

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic-platform-web-client#125]
Hello.
I am testing the push service on a fresh app following the guidelines for Limited setup for Ionic push:

http://docs.ionic.io/v2.0.0-beta/docs/push-limited-setup

After adding the phonegap plugin: 

` ionic plugin add phonegap-plugin-push`

I get this:

```
Updated the hooks directory to have execute permissions
Fetching plugin "phonegap-plugin-push" via npm
Error: Variable(s) missing (use: --variable SENDER_ID=value).
```

I am missing something?
I have to register somewhere?
But i don't see that specified in the guide.

**Comment by Fuiste** [comment]
Currently we use the GCM sender ID you specify in your config, so you can simply install the push plugin with

`ionic plugin add phonegap-plugin-push --variable SENDER_ID=some-value` as stated.

We're going to be moving to the Ionic Cloud https://github.com/driftyco/ionic-cloud repo moving forward as well (It's the same platform web client, just the latest version with our updates to configuration discussed [here](https://github.com/driftyco/ionic-platform-web-client/issues/41))
