### ISSUE TITLE
Doesn't work with ionic2 ionic@beta

### ISSUE THREAD

**Issue by lthh89vt** [driftyco/ionic-platform-web-client#126]
Can't run

`ionic add ionic-platform-web-client`

Got this message: This method is deprecate

**Comment by dwieeb** [comment]
@lthh89vt We're hard at work getting this ready for Ionic 2 projects. The `ionic add` command and the `ionic-platform-web-client` are both deprecated. For v2 projects, we recommend using the new [Cloud Client](https://github.com/driftyco/ionic-cloud-angular). There isn't much documentation for it yet, but if you're up for it, I'd love [some feedback](https://github.com/driftyco/ionic-cloud-angular/issues/1) once you get things set up.
