### ISSUE TITLE
Module ‘ionic.service.analytics’ is not available

### ISSUE THREAD

**Issue by jenshelderweirdt** [driftyco/ionic-platform-web-client#131]
https://forum.ionicframework.com/t/module-ionic-service-analytics-is-not-available/57046

**Comment by orioniota** [comment]
Could you solve this error?

**Comment by ericb** [comment]
This works as expected for me, you may have forgotten to run`ionic io init` and `ionic config build` ?

**Comment by jenshelderweirdt** [comment]
@ericb You are right! `ionic io init` solved the problem.
