### ISSUE TITLE
Push by emails not working + Odd behaviour on token push

### ISSUE THREAD

**Issue by jhitchcock** [driftyco/ionic-platform-web-client#133]
Following the guide, I should be able to send push like this; 

{
  "emails": ["user1@ionic.io", "user2@email.com"],
  "notification": {
    "message": "Hello World!" 
  }
}

However, it doesn't work. I have checked the user exists and the email exists and the user has a push token. Sending by UserID or Push token also works fine

**Comment by jhitchcock** [comment]
The response from checking the status is; 


`{
  "data": {
    "status": "locked",
    "created": "2016-07-29T13:14:22.153927+00:00",
    "config": {
      "profile": "creonew",
      "emails": [
        "user@jhitchcock.com"
      ],
      "notification": {
        "title": "New Alert",
        "message": "You have a new Alert"
      }
    },
    "state": "enqueued",
    "uuid": "7474c3e2-f573-4683-b8b1-8ceaf59b49c1",
    "app_id": "43311612"
  },
  "meta": {
    "version": "2.0.0-beta.0",
    "status": 200,
    "request_id": "6708837d-f519-46c6-ad2e-104ab0259858"
  }
}
`

**Comment by jhitchcock** [comment]
Ok, So I found a page called 'The Anatomy of a push notification' here; 

http://docs.ionic.io/v2.0.0-beta/docs/anatomy-of-a-push-notification

that doesn't show the emails as an option, so I suspect that the documents here; 

http://docs.ionic.io/v2.0.0-beta/docs/push-sending-push (search for 'emails')

are wrong now, and 'emails' doesn't exist any more. Can you confirm? 

So I re-coded everything to use push tokens just to see if that worked.. So firstly, I register the user and save the token to both ionic and my own server. 

The token shows in the user in ionic.io correctly, and also in my database. 

I then send a push message using the API, as so; 

`{
  "tokens": ["fddcea6b13f50d6a707305f35f6eca8ef32a4aae11111834584b3f25d7625b9b"],
  "profile": "creonew",
  "notification": {
    "title": "Hi",
    "message": "Hello world!",
    "android": {
      "title": "Hey",
      "message": "Hello Android!"
    },
    "ios": {
      "title": "Howdy",
      "message": "Hello iOS!"
    }
  }
}`

As per the example in the docs adding my new token and profile only.

The push never arrives, but also oddly the token dissapears from the user push tokens screen in ionic.io!

**Comment by ericb** [comment]
We'll look into this today @jhitchcock. Just FYI, emails, and some of the other targeting options were added recently, so we must have missed adding them to the anatomy of a push notification.

**Comment by jhitchcock** [comment]
Ah ok, well it's great news that emails will exist anyway :) 

Thanks, I'm around all day if you need any more info. 

Also happy to modify docs on readme.io once we confirm stuff

**Comment by devnetics** [comment]
I believe we have identified the core issue and fixed it, but I want to be sure all of your issues are resolved. You should be able to use the example you gave at the top of this issue

Note:
I'm sure you just left this off since you were getting enqueued and not an error, but just to be sure, make sure you include ```"profile":"YOUR_PROFILE" ``` as well, or you'll get an error back (created at [apps.ionic.io/app/YOUR_APP_ID](apps.ionic.io/app/YOUR_APP_ID) -> Settings -> Certificates -> New Security Profile). 

Go ahead and give this another test @jhitchcock, and let me know here. Thanks!

**Comment by jhitchcock** [comment]
Hmm I'm not convinced it's working yet, sorry, seeing exactly the same behaviour when sending by token or email, and the token is still disappearing from the ionic dashboard user, as soon I I have tried to send via the API. 

Example UUID; 
fe5ea52b-105b-49b2-ab33-b25a59e503da

**Comment by devnetics** [comment]
@jhitchcock Can you copy/paste your client code snippet here? 

r.p.s. thanks for pointing that out, I'll make sure that gets updated.

**Comment by ericb** [comment]
@jhitchcock If the token is disappearing, it likely means that it was invalidated, meaning the connection by which you sent the push notification (gcm/apns credentials) told us that the token was not valid. 

You can see the exact reason for a message failure by looking at the [/push/notifications/:notificationid/messages](http://docs.ionic.io/docs/api-push#notifications-list-messages) endpoint.

**Comment by jhitchcock** [comment]
aha @ericb that bit of info will probably lead me to sorting out that issue, it may have been a red herring when re-testing then

I'll confirm once I have tested the original issue is resolved. Thanks again all

**Comment by jhitchcock** [comment]
Ok chaps, I succesfully sent a push message by email and token :) Gracias!
