### ISSUE TITLE
Request headers are not set in Ripple (and possibly other platforms)

### ISSUE THREAD

**Issue by kiasyn** [driftyco/ionic-platform-web-client#134]
Hello,

I've just gotten started with Ionic so I may be missing something completely obvious. 

I'm using Ripple in Chrome to test.

I'm trying to use the Facebook Auth but I'm getting content type header errors. The Content Type header is not being set. I tracked this down in the distribution code to XHR.OPENED etc not being defined. Further investigation shows this code is actually from the browser-request library, which seems to be abandoned so it can't be patched to fix.

Am I missing something, or is this an actual bug?

Cheers,
Sam

**Comment by ericb** [comment]
Our Social Provider Authentication Providers will only work with a physical device or emulator due to the InAppBrowser plugin.
