### ISSUE TITLE
$ionicAnalytics.setGlobalProperties doesen't work

### ISSUE THREAD

**Issue by marcoturi** [driftyco/ionic-platform-web-client#136]
Hi,
I'm trying to use $ionicAnalytics.setGlobalProperties method with no success. In the console and network i see my data sent but on the panel i can't find the properties in the Segments or Pulse Tab.+
        
```
            $ionicAnalytics.register({
                silent: true
            });
 $ionicAnalytics.setGlobalProperties({
                _appName: 'Try'
            });
```

ionic-platform-web-client version 0.7.1

**Comment by dwieeb** [comment]
@marcoturi We have deprecated `ionic-platform-web-client` and we're looking to implement a new analytics solution for the [Cloud Client](https://github.com/driftyco/ionic-cloud). Keep an eye on our blog for analytics support in Ionic 1 & 2.
