### ISSUE TITLE
Bower error, check that "ionic-platform-web-client" exists

### ISSUE THREAD

**Issue by gere1234** [driftyco/ionic-platform-web-client#137]
When i'm running "ionic add ionic-platform-web-client" 

I got this error : 

```
Bower error, check that "ionic-platform-web-client" exists,
or try running "bower install --save-dev ionic-platform-web-client" for more info. (CLI v1.7.16)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:  
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by ericb** [comment]
Have you tried running: `bower install --save-dev ionic-platform-web-client`?

**Comment by ashishbhandari** [comment]
bower install --save-dev ionic-platform-web-client

it also giving me error:

bower invalid-meta  The "name" is recommended to be lowercase, can contain digit
s, dots, dashes
bower not-cached    git://github.com/driftyco/ionic-bower.git#1.3.1
bower resolve       git://github.com/driftyco/ionic-bower.git#1.3.1
bower cached        https://github.com/driftyco/ionic-platform-web-client.git#0.
7.1
bower validate      0.7.1 against https://github.com/driftyco/ionic-platform-web
-client.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github
.com/driftyco/ionic-bower.git", exit code of #128 fatal: unable to connect to gi
thub.com: github.com[0: 192.30.253.113]: errno=No such file or directory

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=No such file or directory

**Comment by ashishbhandari** [comment]
i fixed it by using below command as it as some internal network error: 
C:\dev> git config --global url.https://github.com/.insteadOf git://github.com/

**Comment by dwieeb** [comment]
@gere1234 @ashishbhandari `ionic-platform-web-client` is deprecated. We are asking that people migrate to [the Cloud Client](https://github.com/driftyco/ionic-cloud).
