### ISSUE TITLE
Push notification title is not received via user request

### ISSUE THREAD

**Issue by kuroisuna** [driftyco/ionic-platform-web-client#14]
Hi guys, thanks for the hard work.

When I use the ionic.io dashboard I'm able to add a title for my PN:

![screenshot_2015-10-13-18-36-17](https://cloud.githubusercontent.com/assets/4406617/10470762/608b7e36-71d9-11e5-9c5e-1b02bf5eff69.png)

But when I send the request vía cURL or Postman, I don't receive any title:

![screenshot_2015-10-13-18-38-16](https://cloud.githubusercontent.com/assets/4406617/10470811/a2310734-71d9-11e5-9386-b607457be200.png)

**cURL request:**
```
curl -u PRIVATE_KEY: -H "Content-Type: application/json" -H "X-Ionic-Application-Id: APP_ID" https://push.ionic.io/api/v1/push -d '{"tokens": ["MY_TOKEN"],"production": false, "notification":{ "alert":"Push content/message/alert", "title": "App Push TItle", "android": {"payload": {}}, "ios": {"payload": {}}}}'
```

**Comment by ericb** [comment]
You can do this by placing the title inside the appropriate platform section, but it looks like there may be a bug defaulting to the top level section in the case of the title.

**Comment by kuroisuna** [comment]
Thanks for the quick answer.
Do you mean: `notification.android.title`?

**Comment by ericb** [comment]
Yup

**Comment by danielmilner** [comment]
This may or may not be related (If it's not, I will start a new issue), but I noticed for iOS notifications. If I send a One-Time notification, the push title is sent, but if I schedule a push, the title is absent.

**Comment by Fuiste** [comment]
With the release of the Ionic Platform beta, we've launched a completely new push service where this should no longer be an issue (check out the refactored docs [here](http://docs.ionic.io)).

For future reference, issues pertaining to the platform outside the scope of the client-side js can be posted to https://github.com/driftyco/ionic-platform-issues/issues
