### ISSUE TITLE
Push notification help needed

### ISSUE THREAD

**Issue by asafco4** [driftyco/ionic-platform-web-client#140]
Hi,
It's more of a question, I have this setup:

`// Ionic.io push notifications
var push = new Ionic.Push({
	"debug": true,
	"onNotification": function(notification) {
	    var payload = notification.payload;
	    console.log("onNotification: ", notification, payload);
	},
	"onRegister": function(data) {
		console.log("onRegister: ", data.token);
	}
});`

I need to implement 2 scenarios:
1. When notification is received and the app is open - I want to present a popup - how can I identify this scenario?
2. When notification arrived and app is closed or in the background I want 2 things:
    a. Show the notification on the device = done!
    b. When notification is clicked I want the app to be loaded and navigate the user to specific screen.
     * if there was a way to specify url to be opened when notification is clicked then it's also good cause I'm using branch for deep linking.

I see that the "onNotification" function is called when the notification received but still don't know how to identify scenario 1 from 2

Thanks!

**Comment by ericb** [comment]
The `notification` object passed to your `onNotification` handler has the information you're looking for:

```javascript
function(notification) {
  if(notification.app.asleep) {
    // the app was open,but in the background when 
    // the user clicked the notification
  }
  if(notification.app.closed) {
    // the app was not open when the user clicked 
    // the notification
  }
};
```

If you're using angular, you can simply pass `state` in your payload and call `$state.go(notification.payload.state)` in your notification handler to open the app to a specific state.

**Comment by asafco4** [comment]
@ericb  - Thank you for your reply. 

1. The onNotification handler is called ONLY when the user click the notification or is it also when the app is open and a notification received on the device (and there's no visual notification in the notifications panel)?
2. I use Angular, assuming I added the state to the payload function, how can I set which page to open when I send the notification? Which data on which format I should append to the notification API data?
This is my API call (sorry about indentation, can't seem to get it to be shown well...)
`

json : {
    "tokens" : Array.isArray(deviceTokens) ? deviceTokens : [deviceTokens],
    "profile" : profile,
"notification" : {
"message" : params.message,
"android" : {
"data" : {
"title" : params.title,
"message" : params.message,
"notId" : params.android_notId}},
"ios" : {
"title" : params.title,
"message" : params.message}}}`

**Comment by ericb** [comment]
1. Yes. It should be called in both of those scenarios. However, if it is in the background, and the user does not click the notification, it will not fire the onHandler if they bring the app up from the background.

2. You need to add a [payload](http://docs.ionic.io/docs/push-sending-push#section-adding-custom-data-to-your-notifications) object. You can store whatever information you like and pull it out with `notification.payload.yourkey`

3. I'm not entirely sure, but I don't think so the current push plugin supports that.

4. Yes. The [push plugin](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md) has an option for this in Android called `android.forceShow`

**Comment by asafco4** [comment]
@ericb  - Thank you again for your details reply.

I have last issue, really annoying one with the ionicPopuo:
In my app.js I define the onNotification handler where I say that if a notification was received while the app is open, I will show a popup with that message. This is done so users will not miss the important message even if the app is open.

This is the code, I define all popups in a separate service named popups, which I include in app.js:
`.run(function($ionicPlatform, $ionicAnalytics, $window, $state, $rootScope, utils, $timeout, $location, $ionicPush, configs, popups, ngFB, notifications, skip,$ionicPopup, security) {`

The code is for popup:
`notificationPopup: function(param) {
            var myPopup = $ionicPopup.show({
                template: '<p class="text-center popup-text-custom">' + param.text + '</p>',
                title: param.title,
                cssClass: 'notify-popup',
                buttons: [{
                    text: 'Close',
                    type: 'button-positive',
                    onTap: function(e) {
                        return "connection warning popup closed";
                    }
                }]
            });

            return myPopup;
        }
`

And in app.js I use:
`popups.notificationPopup(param);`

The problem:
if the notification is received when the main app screen is opened it's working great.
if the notification is received in another screen, it doesn't show the button or the title of it.
that screen's controller has both $scope, $rootScope in its function arguments.

See attached photos for the differences.
Any ideas?

Thanks!

![2016-08-26 05 38 09](https://cloud.githubusercontent.com/assets/16074756/17995234/b9d1a8e4-6b25-11e6-9ebc-e63900fdd5cc.png)
![2016-08-26 05 37 41](https://cloud.githubusercontent.com/assets/16074756/17995233/b9d05c28-6b25-11e6-93d1-25e2c33a4e06.png)

**Comment by ericb** [comment]
That seems more of an angular/ionic framework question, but I'd start by checking the scope or timing of values being set before display.
