### ISSUE TITLE
Ionic push notifications not sending to my devices

### ISSUE THREAD

**Issue by riaz61** [driftyco/ionic-platform-web-client#142]
The push service doesn't seem to be pushing my notifications to the device token I provided.

this is whats printed out in the console when i ran my node server. The status code is 201 and the state of the push notification is enqueued.

![push1](https://cloud.githubusercontent.com/assets/16023299/19188548/395f22a2-8c47-11e6-971b-cf7a5e9bfd22.png)
![push2](https://cloud.githubusercontent.com/assets/16023299/19188547/395ba5aa-8c47-11e6-9fca-03ce96212f1a.png)

**Comment by ericb** [comment]
This is normal behavior. Check out the [checking notification status](http://docs.ionic.io/services/push/#checking-notification-status) section of our docs.

**Comment by riaz61** [comment]
But the notifications still aren't being delivered even after several hours. In fact they aren't being delivered at all

**Comment by ericb** [comment]
This means that an incorrect password is being set for your push certificate. Check out the error code explanations listed in [here](http://docs.ionic.io/api/endpoints/push.html#get-messages-message_id) for future reference.
