### ISSUE TITLE
Ionic push notifications error message for notification

### ISSUE THREAD

**Issue by riaz61** [driftyco/ionic-platform-web-client#143]
My status for the notification says "enqueued", then when I check the error message with by getting the notification from the api I get this error message
![push3](https://cloud.githubusercontent.com/assets/16023299/19193679/d909eb58-8c5f-11e6-8ff5-3a0b92942ed2.png)
The error message is mainly "error": "INVALID_CREDENTIAL_PASSWORD"
What does this mean and how can I resolve it so that my notifications are sent.

**Comment by Fuiste** [comment]
Check out the [API documentation](http://docs.ionic.io/api/endpoints/push.html#get-notifications-notification_id-messages) for the messages endpoint for a listing of possible errors and reasons.
