### ISSUE TITLE
Ionic push certificate error

### ISSUE THREAD

**Issue by riaz61** [driftyco/ionic-platform-web-client#144]
So I located which error I received. How do I go about resolving this issue. Should reupload my certificate to ionic settings in the dashboard, or should I make a new certificate or how do I make the correct password for the certificate so the error doesn't happen again?
![push4](https://cloud.githubusercontent.com/assets/16023299/19194096/6ef0aab6-8c61-11e6-9a8f-2070a245397f.png)

**Comment by Fuiste** [comment]
Check out our [security profile docs](http://docs.ionic.io/services/profiles/#attach-credentials-1) for more information on creating and editing profiles.

You should be able to update the password from the Ionic dashboard.

**Comment by riaz61** [comment]
Thank you for the timely responses:)
