### ISSUE TITLE
Plugins not available inside $ionicPlatform.ready, but available inside document.addEventListener("deviceready"

### ISSUE THREAD

**Issue by odinixadmin** [driftyco/ionic-platform-web-client#17]
Using web-client: "ionic-platform-web-client": "~0.1.1"

All my plugins are not available inside $ionicPlatform.ready. However they are available inside document.addEventListener("deviceready". Also the console log statement "Ionic Core: plugins are ready " is printed before my "devideready" listener invoked. But the same console log appears after my $ionicPlatform.ready is invoked. For now I am using deviceready event listener as a workaround.

I bootstrap Angular manually like this:
	    angular.element(document).ready(function() {
		    angular.bootstrap(document, ['appname']);
	    });	

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.0
Ionic App Lib Version: 0.5.1-beta.0
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.3
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by ericb** [comment]
Forgive me if I've overlooked something, but I'm not entirely sure what you're getting at. What error are you actually running into?

**Comment by ddbaron** [comment]
The situation is that $ionicPlatform.ready fires before cordova is fully loaded by ionic-platform-web-client. So all your code in the .run of the module is wrong, e.g.: window.cordova is undefined. You will see, for example, the console message `Ionic Core:, plugins are ready` AFTER you see code execute in `$ionicPlatform.ready`

To overcome this in my project, I manually bootstrap the app once cordova is fully loaded (by ionic-platform-web-client) like this:
```javascript
<script>
    angular.element(document).ready(function () {
        if (window.cordova) {
            console.log("Running in Cordova, will bootstrap AngularJS once 'deviceready' event fires.");
            document.addEventListener('deviceready', function () {
                console.log("Deviceready event has fired, bootstrapping AngularJS.");
                angular.bootstrap(document.body, ['quarky']);
            }, false);
        } else {
            console.log("Running in browser, bootstrapping AngularJS now.");
            angular.bootstrap(document.body, ['quarky']);
        }
    });
</script>
</body>
```
See http://stackoverflow.com/questions/21556090/cordova-angularjs-device-ready

**Comment by dwieeb** [comment]
Should be all fixed up in the [Cloud Client](https://github.com/driftyco/ionic-cloud).

**Comment by solarsaturn9** [comment]
Running the latest version of Ionic 1 and this is still a problem.
