### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by darmie** [driftyco/ionic-platform-web-client#19]
I tried installing ionic-platform-web-client but I am always getting this error. Bower is installed but it says it isn't!!

```You must have bower installed to continue.
Type `npm install -g bower` (CLI v1.7.6)```

**Comment by ericb** [comment]
This is most likely a system issue on your end. You'll need to find out why the reference to 'bower' is not global. It could be that ionic or bower are installed in locations or via users that you do not have permissions to.
