### ISSUE TITLE
Push Error 101: ios device token without spaces fails

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic-platform-web-client#2]
I'm not sure how important it is to protect device tokens, so I will just x them all out...

When my app registers for the push plugin in ios, I see the token output in xcode as the following:
Push Plugin register success: xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx

I also get the following warning:
Invalid callback id received by sendPluginResult

In onRegister, I console.log(data.token), which outputs the token without spaces.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Ionic.io saves the token without spaces for that user in the webapp.

Whenever I try to push using user id or the token without spaces, I get a 101 error. Whenever I push to the token with spaces, the notification goes through correctly.

**Comment by ericb** [comment]
@djangojack That's interesting, I don't think I've ever seen a token with spacing. Do you happen to be using iOS 9?

**Comment by djangojack** [comment]
@ericb No, its iOS 8.4.1

**Comment by djangojack** [comment]
@ericb I created a dummy app on the same device to test push notifications, and the output looks like this:

`2015-10-05 10:26:42.015 testpush[185:3543] Push Plugin register success: <dc69c510 c295102e 350e0040 13a390d2 3c3ee15e 09dee9f9 473cb781 18702abd>
2015-10-05 10:26:42.097 testpush[185:3543] dc69c510c295102e350e004013a390d23c3ee15e09dee9f9473cb78118702abd`

The dummy app pushes fine to the token without spaces, but my real app can only push to the token with spaces.

**Comment by ericb** [comment]
So from everything we know / have seen, I feel like there is a piece missing here or you've hit a once in a million token registration that happens to be misbehaving in our service, the push plugin, or Apple's APNS service. 

If you call `unregister()` and then `register()` again, do you successfully get a new token?

**Comment by ericb** [comment]
closing this as we will track with #7
