### ISSUE TITLE
Deploy update returns "download error" when rolling back (iOS)

### ISSUE THREAD

**Issue by rkistner** [driftyco/ionic-platform-web-client#21]
When rolling back to a revision that is already downloaded (e.g. by switching channels, or triggering a rollback from the web interface), this happens:

1. Call `Deploy#update()`.
2. `check()` returns true (update available).
3. `download()` return false (update is already downloaded).
3. `update()` rejects with `"download error"`.

This makes the app think it could not download an update, even though it succeeded. However, `IonicDeploy.m#download` does saves the `uuid`, so the update is correctly applied on the next application start.

**Comment by ajoslin** [comment]
I'm getting this as well, except not on a rollback -- getting this on every download.

Bump. Anyone found a solution for this? cc @ericb 

Just let me know what I need to do to help you debug. More information, etc.

**Comment by ericb** [comment]
@ajoslin Can you provide the xcode or android logs, and maybe the app console logs as well?

**Comment by ajoslin** [comment]
Hi @ericb, I apologize for the delay.

Here is my XCode log: http://sebsauvage.net/paste/?ecfdf6e62a54f0a0#cZX/b2DyYEA5MVeLe+ZW/ETbiZ41JfjFLJka/KC/oH0=

I refreshed after one try, that's why you see it start up twice.

The app console logs aren't very useful and can be contained in one screenshot: http://ajoslin.co/14SDj

**Comment by ericb** [comment]
@ajoslin I took a look at the logs. You're actually running into the iOS9 App Transport Security issue. We use S3 as a backend to host deploy files and unfortunately the aws certificates do not meet the requirements of Apple's ATS. Amazon has a [blog post](https://mobile.awsblog.com/post/Tx2QM69ZE6BGTYX/Preparing-Your-Apps-for-iOS-9) explaining how you can circumvent the issue. Hopefully this is only a temporary issue and the exception can be removed in the future.
