### ISSUE TITLE
payload in null in development push and in production push.

### ISSUE THREAD

**Issue by venkateshwarv** [driftyco/ionic-platform-web-client#24]
<pre>
_payload: null
_raw: Object
additionalData: Object
coldstart: false
foreground: true
__proto__: Object
message: "Message"
title: "DEVELOPMENT PUSH"
__proto__: Object
app: PushMessageAppStatus
count: null
image: null
payload: (...)
sound: null
text: "Message"
title: "DEVELOPMENT PUSH"
__proto__: PushMessage
</pre>

The payload is null in both the cases, even if i send a payload from Ionic.io push.

**Comment by ericb** [comment]
Payloads are not supported in dev_push mode.
