### ISSUE TITLE
Ionic Deploy: Offer some way to develop and test functionality in the browser / using `ionic serve`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-platform-web-client#25]
It would be awesome if Ionic Deploy actually 'worked' while developing your app: Checking for updates, receiving answers that an update is available or not available, actually pseudo-downloading some file would be great to develop the UI used to represent Deploy in my app. 

Right now it only says `Ionic Deploy: Checking for updates`in the console, but no request is sent out and nothing happens. I have no way to see what my UI looks like, if the callbacks actually work.

Of course there are some limitations, as e.g. of course it shouldn't really update the app - but this could be handled by some console.log calls to make the user aware of it. Also some helper methods that set "update available on next try" or "no update available on next try" you can implement as debug buttons would complete the feature set. Maybe this could be some kind of "mock" that is automatically used on local development, I don't know the best way to achieve this.

What do you think?

**Comment by johnfakeacc** [comment]
+1

**Comment by dwieeb** [comment]
Moved to https://github.com/driftyco/ionic-platform-web-client/issues/25
