### ISSUE TITLE
bower.json: Why is `ionic-platform-web-client` only a devDependency?

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-platform-web-client#26]
Hey,

sorry if this is a dumb question but I am cleaning up my project right now and noticed that `ionic-platform-web-client` is only listed in `devDependencies` in my bower.json. Is this correct? Or shouldn't it bet part of `dependencies` with all the other libraries my app needs in production?

Thanks.

**Comment by ericb** [comment]
All the components are added as dev dependencies as far as I know. Bower is never used in any kind of production environment. You're either serving up a finished www directory or running a binary (with all the dependencies already packaged) on your device.

**Comment by piotrowski** [comment]
Ok thanks, was just wondering. 

Thankfully no more bower with ionic2 afaik...
