### ISSUE TITLE
Feature request: disable logging

### ISSUE THREAD

**Issue by eikooc** [driftyco/ionic-platform-web-client#27]
Hey it would be nice if it was possible to disable the logging to the console performed by the library

**Comment by strttn** [comment]
+1

Difficult to see the things I want to see in the log because of the noise from analytics

**Comment by strttn** [comment]
Did a bit more digging and it turns out this feature has been added back in.

Just need to pass silent = true into the register function via the options object.

e.g.
`$ionicAnalytics.register({ silent: true });`

**Comment by ericb** [comment]
@strttn Sort of -- I'm keeping this open as that option is only for analytics, and is a straight on/off value, I'd like to be able to globally configure logging for the platform client, so you can get different levels of logs as well as tuning which components will log at various levels

**Comment by strttn** [comment]
Ok, fair enough. Makes sense. :+1:

**Comment by dwieeb** [comment]
For general logging, see this issue: https://github.com/driftyco/ionic-platform-web-client/issues/53

Closing this as a duplicate.
