### ISSUE TITLE
Push to ios token sent to android device in web interface

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic-platform-web-client#28]
In the web app, user 1 has an android and an ios token. 

In the one time notification interface, If I send a notification to the ios token, it goes to the android device. The ios device doesnt get anything.

For reference, look at message 5d816da489a811e5aae6c679ee8a10f4

{"ios":{"sent":1,"failure_reason":"Push Error Code 102: See http://docs.ionic.io/docs/push-error-codes for more info.","success":true},"status":"Sent","errors":[],"android":{"sent":1,"failure_reason":"","success":true},"app_id":"952ae98e"}

**Comment by ericb** [comment]
According to that message id, two tokens were sent (1 Android, 1 iOS). The iOS token was most likely invalid or the provisioning profile could be setup incorrectly.
