### ISSUE TITLE
Cannot sign off and sign in with new user

### ISSUE THREAD

**Issue by razmik** [driftyco/ionic-platform-web-client#30]
There is no method to clear the current user in Ionic.User.current(). So once you sign off and sign in with new user(to the app), the new user cannot be saved because it doesn't give a fresh Ionic.User.

Solution would be;

Ionic.User.clear() which will clear the "AppUserContext ".

Reference: ionic-platform-web-client/src/core/user.js: line 219

  static current(user) {
    if (user) {
      AppUserContext = user;
      UserContext.store();
      return AppUserContext;
    } else {
      if (!AppUserContext) {
        AppUserContext = UserContext.load();
      }
      if (!AppUserContext) {
        AppUserContext = new User();
      }
      return AppUserContext;
    }
  }

**Comment by ericb** [comment]
`current()` can take a fresh `User` object to register a new user as the current user.

Example:

```javascript
var newUser = new Ionic.User()
Ionic.User.current(newUser);
```
