### ISSUE TITLE
Applying split function on a NON string variable

### ISSUE THREAD

**Issue by Diones** [driftyco/ionic-platform-web-client#31]
Guys, I've gotten this error: ```i.split is not a function``` while clicking on map created by [leaflet-directive](https://github.com/tombatossals/angular-leaflet-directive).

The line code can be found here: https://github.com/driftyco/ionic-platform-web-client/blob/master/dist/ionic.io.bundle.js#L2499
```javascript
        var className = element.className;
        if (className) {
          var classes = className.split(' ');
          for (var i = 0; i < classes.length; i++) {
            var c = classes[i];
            if (c) {
              selector += '.' + c;
            }
          }
        }
```

I logged the variables in order to know what kind of object split function was receiving. My log:
```
element: {"_leaflet_pos":{"x":-180,"y":-241},"_simulatedClick":true} 
classname: {}
type: object
```

The code check if `className` exists. As you can see, the `className` exists, however, it is an empty object. So, when trying to split, the error is thrown.

**My suggestion is to check if `className` is a string before trying to split it.**

p.s.: I think this is related to Ionic Analytics, because I got the log print on click, whatever is the place. When the click occurs on Ionic buttons for instance, I get the following log: 
```
element: {"$$hashKey":"object:43"} 
classname: "icon ion-ios-person-outline" 
type: string
```

**Comment by luiscvalmeida** [comment]
+1

**Comment by luiscvalmeida** [comment]
Also, I got this after wiring up Ionic Analytics.

**Comment by fgenoese** [comment]
+1
Happening to me when clicking on a chart generated with d3js (= svg).

**Comment by Tobi042** [comment]
Seems to be related to https://github.com/driftyco/ionic-service-analytics/issues/34 .
Fix is the same: Don't use the minified version and replace the given line (2503 in v0.7.1) 
`var classes = className.split(' ');`
with
`var classes = ('' + className).split(' ');`

Creating PR now.
