### ISSUE TITLE
docs: Docs on deploy channel name vs channel tag

### ISSUE THREAD

**Issue by matthewlloyd** [driftyco/ionic-platform-web-client#32]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The documentation on deploy channels could benefit perhaps from being a little clearer on the difference between the channel name and the channel tag. The method to set the channel tag is setChannel. Accidentally calling setChannel with the channel name can cause the app to pull from the wrong channel, if the channel name and the channel tag happen not to be equal.

Also it seems like channel names and tags were kept separate for a reason - presumably there is a use case - would be really nice to see the use case documented and explained!</span>

<span is-issue-template></span>

**Comment by dwieeb** [comment]
@matthewlloyd The tag is just a machine name of the name. It's just a convenient way to reference a channel if the name is complex or has been changed.

I've added more about this in our new docs: http://docs.ionic.io/services/deploy/

If you haven't already, we are recommending people migrate to the [Cloud Client](https://github.com/driftyco/ionic-cloud).
