### ISSUE TITLE
Analytics local storage entry used but not cleared when ionic.service.analytics added to a project but $ionicAnalytics.register() not called

### ISSUE THREAD

**Issue by tomasvarg** [driftyco/ionic-platform-web-client#35]
My ionic app was draining 100% cpu (run in Chromium, served by "ionic serve"), I've found out it was caused by very a big ionic_analytics_event_queue_APPID entry in local storage (about 4MB).

I had ionic.service.analytics (ionic-platform-web-client v0.2.1) added as a dependency for the base angular module and prepared some custom analytic events (app bootstrap, login, logout) but as the app was still in development phase, I didn't have $ionicAnalytics.register() called anywhere (mainly because I was bothered by the Analytics overusage of console.log).

This leads to quick growth of the ionic_analytics_event_queue_APPID local storage entry, which is not being cleared.

It happens even when only the "ionic.service.analytics" entry is added as a dependency for an angular module and no further $ionicAnalytics injections.

I'd say there should be a method for turning the Analytics on/off so the functionality (i.e. code) can be prepared in advance and used as needed, as done now it would have to be enwrapped in a custom module to achieve this, which seem unnecessarilly superfluous.

A method for decreasing Analytics console.log promiscuity would also be very pleasant.

**Comment by dwieeb** [comment]
@tomasvarg We've deprecated the `ionic-platform-web-client` and will be providing a new analytics solution for Ionic 1 & 2 in the [Cloud Client](https://github.com/driftyco/ionic-cloud). Keep an eye on our blog!
