### ISSUE TITLE
ionic add ionic-platform-web-client not working

### ISSUE THREAD

**Issue by ituhin** [driftyco/ionic-platform-web-client#36]
is it working with the latest ionic 1.2.1 ?

i am getting 

Failed to find the bower component "ionic-platform-web-client".
Are you sure it exists? (CLI v1.7.12)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C62b

this too didnt work....
bower install --save ionic-platform-web-client

bower not-cached    git://github.com/driftyco/ionic-bower.git#1.2.1
bower resolve       git://github.com/driftyco/ionic-bower.git#1.2.1
bower cached        git://github.com/driftyco/ionic-platform-web-client.git#0.2.1
bower validate      0.2.1 against git://github.com/driftyco/ionic-platform-web-client.git#*
bower ENORESTARGET  No tag found that was able to satisfy 1.2.1

Additional error details:
Available versions in git://github.com/driftyco/ionic-bower.git: 1.2.1-nightly-1865, 1.2.1-nightly-1864, 1.2.0, 1.2.0-nightly-1862, 1.2.0-nightly-1860, 1.2.0-nightly-1858, 1.2.0-nig.............

[EDIT]
actually nothing is working with ionic 1.2.1
for an example... bower install moment also doesnt work in a ionic 1.2.1 project

**Comment by Kojee** [comment]
not working for me either. 
Git is installed.

**Comment by SunilRumbaLama** [comment]
Try bower install --save-dev ionic-platform-web-client instead.

**Comment by mrzmyr** [comment]
Doesn't work for me either.

**Comment by ericb** [comment]
as @SunilRumbaLama has mentioned running `bower install --save-dev ionic-platform-web-client` can provide you with a more detailed error message. You likely have an issue unrelated to the platform-client directly.

**Comment by furtadodiegos** [comment]
bower install work's fine with me. thanks
