### ISSUE TITLE
don't put config in the lib folder

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic-platform-web-client#38]
Putting config in the lib folder definitely an anti-pattern. Please don't do that!

Somehow there needs to be a way to put this in a JSON file. Maybe gulp task is needed to get it into the right place, or maybe the ionic-cli could take care of it on build, etc.

This is an extension of #29 I guess.

**Comment by glasset** [comment]
hey you can check this issue
https://github.com/driftyco/ionic-platform-web-client/issues/4#issuecomment-165987374

**Comment by kylefox** [comment]
This can likely be closed in favour of https://github.com/driftyco/ionic-platform-web-client/issues/41 (cc @ericb)
