### ISSUE TITLE
can register users & push tokens with wrong public api_key

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic-platform-web-client#39]
I deleted all api keys in the web app and then created a new api key.

Without changing my app at all, I could still create users & add push tokens etc. Only the \write api endpoint gave me a 401 rejection.

**Comment by ericb** [comment]
Yup, this is because the current users endpoints are not restricted -- the current endpoints are meant as a generic data store. We're going to have some information about this in our next update.
