### ISSUE TITLE
Cannot read property 'get' of undefined BaseSettings

### ISSUE THREAD

**Issue by Jerome2606** [driftyco/ionic-platform-web-client#4]
Hi,

I get an error when I try my app after add ionic-platform-web-client.
```
3442: this._settings
undefined
Uncaught TypeError: Cannot read property 'get' of undefined
```
at line 3442 in ionic.io.bundle.js, it point me on BaseSettings.
this._settings is undefined.
EDIT: this happens when script try to get the "dev_locations" BaseSettings

This is the portion code in ionic.io.bundle.js that cause error:
```
var BaseSettings = (function () {
  function BaseSettings() {
    _classCallCheck(this, BaseSettings);

    this._settings = null;
    return this;
  }

  _createClass(BaseSettings, [{
    key: "factory",
    value: function factory(name, func) {
      this._settings = func();
      return this;
    }
  }, {
    key: "get",
    value: function get(name) {
        console.log("3442: this._settings");
        console.log(this._settings);
      return this._settings.get(name);
    }
  }, {
    key: "finish",
    value: function finish() {
      return this;
    }
  }]);

  return BaseSettings;
})();

var temp = new BaseSettings().factory('$ionicCoreSettings', function () {
  "IONIC_SETTINGS_STRING_START";"IONIC_SETTINGS_STRING_END";
}).finish();

var Settings = (function () {
  function Settings() {
    _classCallCheck(this, Settings);
    
    this._locations = {
      'api': 'https://apps.ionic.io',
      'push': 'https://push.ionic.io',
      'analytics': 'https://analytics.ionic.io'
    };
      console.log("3469: this");
    console.log(this);
    this._devLocations = this.get('dev_locations');
    if (!this._devLocations) {
      this._devLocations = {};
    }
  }
```

I have this in settings.js:
```
class BaseSettings {

  constructor() {
    this._settings = null;
    return this;
  }

  factory(name, func) {
    this._settings = func();
    return this;
  }

  get(name) {
    return this._settings.get(name);
  }

  finish() {
    return this;
  }
}

var temp = new BaseSettings().factory('$ionicCoreSettings', function() {
  "IONIC_SETTINGS_STRING_START";"IONIC_SETTINGS_STRING_END";
})

.finish();

export class Settings {

  constructor() {
    this._locations = {
      'api': 'https://apps.ionic.io',
      'push': 'https://push.ionic.io',
      'analytics': 'https://analytics.ionic.io'
    };
    this._devLocations = this.get('dev_locations');
    if (!this._devLocations) { this._devLocations = {}; }
  }

  get(name) {
    return temp.get(name);
  }

  getURL(name) {
    if (this._devLocations[name]) {
      return this._devLocations[name];
    } else if (this._locations[name]) {
      return this._locations[name];
    } else {
      return null;
    }
  }
}

```

**Comment by Jerome2606** [comment]
Ok, after make a simple app test with Ionic, it appears that ionic io init write some lines in ionic.io.bundle.min.js
You make a message on the site docs.ionic.io
```
Custom App Structures

If you use a custom app structure and do not use the default file structure, we will not make any modifications, and you will need to manually edit your own files.

If you are currently using a custom location for the /libs directory, we will not be able to generate the settings, and your app will break.

Currently, we do not have a way to specify the location of your libs directory, but we intend to allow this in a future update. If you need to get around this, you will have to install the core library to the normal directory, set up a process to run ionic config build, and copy the file to your custom lib directory.
```

But, you don't specify which lines are modified...

Here's the difference, I have:
```
"IONIC_SETTINGS_STRING_START";
    var settings = {
                    "dev_push": true
                };
                return {
                    get: function(setting) {
                        if (settings[setting]) {
                            return settings[setting];
                        }
                        return null;
                    }
                };
    "IONIC_SETTINGS_STRING_END";
```

after copy these lines in my "custom app structure" all seems to work 

I suggest you to write more details about the modifications on the documentation.
What I need to modify for production ? dev_push = false ?

**Comment by ericb** [comment]
Perhaps you misunderstood the comment about copying the data to your custom structure. You should be copying the entire file, not the specific injected code. That would be incredibly error prone and tedious for you to do each time you make a config change. It would be better for you to setup a gulp task of some sort that would build the config and then copy the entire file to your custom directory.

That aside, we intend to allow you to the set the custom location of your libs in a future CLI update.

**Comment by Jerome2606** [comment]
The lib location folder is write in .bowerrc file.

**Comment by ericb** [comment]
Yes, but that's not the only way a custom structure can be obtained, and that's only for bower installations.

**Comment by Jerome2606** [comment]
Ok, thanks for your explanation.

I will try to add a grunt task for my config

**Comment by ericb** [comment]
No problem, hopefully we can get that feature in sooner rather than later for those of you with custom structures!

**Comment by matthieu-D** [comment]
This is kind of fucked up, ionic starter uses bower_component and app.
Ionic starter never use www/lib (unless I made some modification to the grunt tasks or maybe my ionic starter is way too old)

**Comment by casoetan** [comment]
Thanks @matthieu-D. That worked. Hope a fix comes soon.

**Comment by glasset** [comment]
with a gulp  task     
```
///gulp.config.js
	var config = { [...]
		libclientionic: src + 'lib/ionic-platform-web-client/dist/' 
        };

///gulfile.js
var fs = require('fs');

 gulp.task('ioconfig', function () {
	var src = config.libclientionic + 'ionic.io.bundle*.js';
	var ioconfig = fs.readFileSync(".io-config.json", "utf8").slice(0, -1);
	var start = '"IONIC_SETTINGS_STRING_START";var settings =';
	var end =  '; return { get: function(setting) { if (settings[setting]) { return settings[setting]; } return null; } };"IONIC_SETTINGS_STRING_END"';
	var replaceBy = start + ioconfig + end;

	log('inject .io-config in ionic.io.bundle.js');
	gulp.src(src)
	.pipe(replace(/"IONIC_SETTINGS_STRING_START.*IONIC_SETTINGS_STRING_END"/, replaceBy))
	.pipe(gulp.dest(config.libclientionic));
});

///.io-config.json
"dev_push":false,"app_id":"123","api_key":"dwd2100","gcm_key":"102394586"}
```

**Comment by another-guy** [comment]
Hi folks, I have the same issue here. What is the recommended fix for it? 

The solution by matthieu-D works for me, however it seems to be hacky.

**Comment by matthieu-D** [comment]
I'm currently moving to another solution : OneSignal which seems to be working better.
Haven't finished the migration though ... And you can only use real device.

**Comment by matthieu-D** [comment]
OneSignal is easy to install on iOS although it's a push to device instead of push to user.

**Comment by kylefox** [comment]
I ran into this issue as well — I had moved my bower components from `./www/lib` to `./bower_modules` in order to reduce the size of the `www` package. @glasset's gulp task worked for me, thank you! :+1:

It seems like there's probably a more elegant way of making the data in `.io-config.json` available to the app. Although I'm not a fan of global variables, I believe they can be appropriate in config/settings scenarios like this.

One idea might be to process `.io-config.json` to `www/js/io-config.js` and declare a global variable:

```javascript
var IONIC_CORE_SETTINGS = {"app_id":"abc","api_key":"123","dev_push":true}
```

and then in `ionic.io.bundle.js`:

```javascript
var temp = new BaseSettings().factory('$ionicCoreSettings', function () {

  // Look for the global variable processed into www/js/io-config.js
  var settings = IONIC_CORE_SETTINGS || {};

  return {
      get: function(setting) {
        if (settings[setting]) {
          return settings[setting];
        }
        return null;
      }
  };
}).finish();
```

Still not elegant, but I don't think it's as brittle as modifying a dependency's code (which could live anywhere). Also, I'm not 100% sure of ALL the requirements or background which lead to the decision to modify code in the first place, so my suggestion might very well be a bad idea :)

**Comment by ericb** [comment]
@kylefox Thanks for taking the time to provide your suggestion. 

There is definitely a number of different scenarios we can take for the future of the Ionic Platform config, and I am open to changing this to suit a wider audience. I would say the only real requirement is that we can depend on the config being defined pre-instantiation of the Ionic Platform code and potentially defined in a way that 3rd party libs can also utilize both on and off device.

Because everyone's build process can be so vastly different, I'd love hear more about everyone's workflow so that perhaps we can choose a more pliable config setup.

**Comment by kylefox** [comment]
@ericb No problem.

In terms of my custom setup, the biggest changes I've made are:

* All code (JavaScript, Sass, and Templates) lives in `app` rather than `www` and are compiled/concatenated by gulp (ex: `www/js/app.js` and `./www/css/app.css`).
* Bower components are installed to `bower_modules` rather than `www/lib`, and then I have a gulp task which concatenates the script files I'm actually using into `www/js/libs.js`. ([Here's a gist from my gulpfile.js](https://gist.github.com/kylefox/c7878177a07ec63d442a))

I made these changes in order to keep the `www` (and resulting zip file) as small and simple as possible. Before I made the change my `./www` folder was ~14MB (!) due to the huge tree of installed bower modules.

I would *love* if Ionic 2 comes with a workflow baked in. By far my biggest challenge with Ionic has been around workflow, file/folder structure, and the implications those can have on the Ionic services (serve, deploy, push, etc). Happy to provide more details about my specific setup if you like.

(Aside — perhaps this is best discussed in a new issue?)

**Comment by domharrington** [comment]
@glasset thanks for the gulp task, a variation on this worked for me. Would be great to have an official supported method for this in future.

Here's a link to the docs for the automatic code modifications that are performed: http://docs.ionic.io/v1.0/docs/io-service-modules#section-modifications.

Could this not be achieved by having an angular provider which is configurable via a `module.config` block? Then it could be achieved however people want to.

**Comment by tobiasmuecksch** [comment]
@ericb I'm encountering the same problem.

My workflow looks like this:

**Folder structure:**
`project_name/`
`project_name/src` <- index.html, app.js and so an are here
`project_name/bower_components` <- dependencies are here
`project_name/dist` <- project is compiled and copied over here
`project_name/dist/lib` <- all dependencies are copied here
`project_name/ionic` <- this folder is created by the blank ionic starter

**Build process:**
1. compile sass
2. minify html and js
3. copy files in `src/**` and in `bower_components` over into the `list` folder
4. copy all files in the `dist/**` folder over into the `ionic/www` folder
5. execute `ionic build`


I liked the previous solution for configuration much more:
 ```
// Identify app
		$ionicAppProvider.identify({
			// The App ID (from apps.ionic.io) for the server
			app_id: 'xxxxxx',
			// The public API key all services will use for this app
			api_key: 'xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx',
			// The GCM project number
			gcm_id: 'xxxxxx xxxxxx'
		});
```

**Comment by LukasRos** [comment]
I also have a custom project structure for the same reasons that @kylefox already mentioned; to keep the node_modules and bower_components outside www and just copy the required files to keep the www/lib directory as small as possible.
Also `ionic config build` doesn't do anything for me, so I'm doing something similar to what @matthieu-D did by replacing the configuration within the file but I've automated it with grunt (which I'm already using in my build process).

Here's an excerpt from my Gruntfile for reference:

    'string-replace': {
          config: {
            files: [{
              src : ['node_modules/ionic-platform-web-client/dist/ionic.io.bundle.min.js'],
              dest : 'www/lib/',
              expand : true,
              flatten : true
            }],
            options: {
              replacements: [
                {
                  pattern: '"IONIC_SETTINGS_STRING_START";"IONIC_SETTINGS_STRING_END"',
                  replacement: 'var settings = <%= grunt.file.read(".io-config.json") %>; return { get: function(setting) { if (settings[setting]) { return settings[setting]; } return null; } };'
                }
              ]
            }
          }

**Comment by gruppjo** [comment]
As I'm trying to integrate **ionic-platform-web-client** and the **Ionic CLI Platform commands** into [Generator-M-Ionic](https://github.com/mwaylabs/generator-m-ionic) I came across this issue.

I wrote a gulp task that injects the `api_key` and `app_id` into the ionic-platform-web-client library files (both of them, the minified and regular version). I thought this might help some of you guys. In case you're interested check it out [here](https://github.com/mwaylabs/generator-m-ionic/blob/dev/generators/ionic-platform/templates/gulp/ionic.js). It uses `gulp-inject` and is easy to adapt for your own file-structure.
