### ISSUE TITLE
Please add hint on Readme doc to install spawn-sync NPM package

### ISSUE THREAD

**Issue by marwan2** [driftyco/ionic-platform-web-client#40]
To ensure that most of people willn't got an error as this:
> Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.

Please refer at the Read.me to run the following command to install spawn-sync:
> npm install spawn-sync

**Comment by Fuiste** [comment]
Thanks for the heads up, but edits to the docs can be suggested through the 'suggest edits' feature on docs.ionic.io.
