### ISSUE TITLE
Unable to call the method removePushToken succesfully

### ISSUE THREAD

**Issue by lucasarts321** [driftyco/ionic-platform-web-client#44]
I am working with push notifications and i can load users successfully but whenever i try to remove the token i am unable to achive it. My code works like this:

                   if (window.localStorage['user'] != $scope.data.username) {
                    var success = function(loadedUser) {

                      Ionic.User.current(loadedUser);
                      console.log('user loaded');

                    };

                    var failure = function(error) {
                      console.log('something went wrong');
                    };

                    Ionic.User.load(window.localStorage['guid']).then(success, failure);
                    var push = new Ionic.Push();
                    var userOld = Ionic.User.current();                 
                    userOld.removePushToken(window.localStorage['token']);
                    userOld.save();

                    }  
The code works fine and load the user but dont remove the token associated with this user which is stored in window.localStorage['token'].  This code is inside the log in after this i registered the new user ; this way i secure only 1 user get notification in the device. I have been stucked with this for 3 days now any help will be appreciated.

**Comment by ericb** [comment]
When you call `removePushToken`, you are only telling us to disassociate that token with the specific User you were acting on. This does not invalidate the token in any form, so if you were to still send a push notification using that token, it would indeed still be delivered. 

If you wanted to invalidate the token you would call `push.unregister();`

It's also possible to get a token for a device, invalidate that token, and then register again with the *same* token, or a new one. In the case of the latter, it takes the GCM/APNS servers awhile to actually stop sending to those tokens (even though they have registered your device with a new token), so it would be possible to get more than 1 message delivered to the same device. In the case of the former, you could just be removing the token, but then re-registering the token the next time you run `push.register`.

Outside of that, you may just need to verify the token you are storing in local storage is the correct token.
