### ISSUE TITLE
bug: no finish method in Ionic.Push ?

### ISSUE THREAD

**Issue by johnrobertcobbold** [driftyco/ionic-platform-web-client#46]
According to https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1, "When you receive a background push on iOS you will be given 30 seconds of time in which to complete a task. If you spend longer than 30 seconds on the task the OS may decide that your app is misbehaving and kill it. In order to signal iOS that your on('notification') handler is done you will need to call the new push.finish() method."

The finish method does not seem to be available in Ionic.Push. Would I be correct ?

**Comment by ericb** [comment]
That is correct. A new version will be published soon which will allow you to get the plugin so you can call finish directly. I'll keep this open until then.

**Comment by rpalacio86** [comment]
+1

**Comment by ericb** [comment]
The latest version of the platform client now has a `getPushPlugin` method which you can use to call finish.
