### ISSUE TITLE
Push onReady event not firing in Chrome dev mode

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic-platform-web-client#47]
Trying to test ionic in dev_push = true mode, did everything according to http://docs.ionic.io/docs/push-from-scratch but in
```javascript 
$ionicPlatform.ready(function() {
    var push = new Ionic.Push({
      "debug": true
    });

    push.register(function(token) {
      console.log("Device token:",token.token);
    });
  });
```

the console never logs out anything after the first refresh. It means: when opening the tab/window at the first time it works, then it does not. In FF and even in IE it works after any reload. I suspect my chrome has some specific issue.

Additionally: the IonicPlatform._pluginsReady = true at first load and = false on subsequent refreshes.
Same with IonicPlatform.cordovaPlatformUnknown: true and false after.

In the console there are something more useful, at first load:

Ionic Core: init
ionic.io.bundle.js:3243 Ionic Core: searching for cordova.js
ionic.io.bundle.js:3243 Ionic Core: attempting to mock plugins

at second reload:
Ionic Core: init
ionic.io.bundle.js:3243 Ionic Core: searching for cordova.js
ionic.io.bundle.js:3243 Ionic Core: injecting cordova.js

as you can see after the second reload it would not mock plugins but try to inject cordova.js resulting that the pluginsready will never be true and event will never be fired.

Any ideas?

**Comment by barocsi** [comment]
Turned out to be duplicate of https://github.com/driftyco/ionic-platform-web-client/issues/22

**Comment by dwieeb** [comment]
Closing this, as I believe it is resolved. We're also removing dev push for the time being until we rethink it. In our new documentation we will only be supporting native push notifications.
