### ISSUE TITLE
Error in callback when starting app after receiving push

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic-platform-web-client#49]
Hi, 

Everything works fine with Push onNotification when the app is active. However when the app starts it always prints out an error:
```javascript
Error in Success callbackId: PushNotification295000169 : TypeError: Cannot read property 'id' of undefined
```
I seem to be initializing the callbacks in a wrong order? 
Any ideas? Thanks!

**Comment by ericb** [comment]
Interesting. I think that may be coming from the push plugin itself and not the platform client, but I'll look into it either way.

**Comment by Fuiste** [comment]
Are you still having this issue?  if so, can you provide your push service instantiation code?
