### ISSUE TITLE
`Analytics.track` mutates event data

### ISSUE THREAD

**Issue by kylefox** [driftyco/ionic-platform-web-client#50]
I've been kicking the tires of Ionic Analytics (awesome so far!) and stumbled upon this because I'm also using Mixpanel.

The `Ionic.Analytics.track(name, data)` method will actually _modify_ `data`, which can cause unexpected side effects:

```javascript
var eventData = {awesome: true};
$ionicAnalytics.track('Foo', eventData);

// `eventData` now contains all of my global properties,
// as well as some Ionic specific data: _app, _user, _ui, keen
// Ex: Object.keys(eventData).length === 5

// This obscure data is now being sent to Mixpanel:
mixpanel.track('Foo', eventData);
```

Obviously in my specific scenario the fix is to perform `mixpanel.track()` _before_ `$ionicAnalytics.track()`.

However, I think it's generally a bad idea for a method to mutate parameters in this fashion. It would be much better to treat `eventData` as immutable and use `angular.extend` instead of modifying the object directly.

Cheers!

**Comment by fabricekabongo** [comment]
:+1:  (1 billion time!)
I use Ionic, GA and another one (I always forget the name). It's painful.

**Comment by mlynch** [comment]
Hey guys, can you try the version in master? Should be fixed. Thanks!

**Comment by kylefox** [comment]
I just did a quick test with this commit, and it seems to have resolved the issue :+1:

However, going to hold off actually updating my app until there's a tagged release.

Thanks @mlynch !

**Comment by ericb** [comment]
@kylefox There should be a new tagged release next week... along with some new goodies ;) +1:
