### ISSUE TITLE
404 when call push.unregister()

### ISSUE THREAD

**Issue by peresbruno** [driftyco/ionic-platform-web-client#52]
404 when calling push.unregister()

Hello.

I'm working with pushes in my app. My code works fine and i'm receiving pushes from server correctly, but when calling push.unregister(), the post to apps.ionic.io/api/v1/app/<<app_id>>/push/invalidate-token responds with a 404 error ("Request Failed with status code of 404"). The push.register() function is called when the user log in and your callback returns a token. My app is in production mode (ionic config set dev_mode false). I tried reconfigure my app many times following the step by step described here: http://docs.ionic.io/docs.

Any help will be appreciated.

**Comment by ericb** [comment]
Has your token actually been registered? If it hasn't previously been stored on our system, it would give a 404.

**Comment by peresbruno** [comment]
Hello @ericb 

Sorry, you are right. I added  user.addPushToken(pushToken) and user.save() in registration callback and push.unregister() and now push.unregister() is working.

Thanks!
