### ISSUE TITLE
Any way to override the logger?

### ISSUE THREAD

**Issue by domharrington** [driftyco/ionic-platform-web-client#53]
Is there any way to pass in a different logger as an option? At the moment it appears to be hardcoded to use `console` but this clutters up the chrome inspector and karma test runner unnecessarily.

https://github.com/driftyco/ionic-platform-web-client/blob/master/src/core/logger.js

**Comment by ericb** [comment]
Sort of. You would need to override the Logger class to a version where the silence option is defaulted to true. 

This is definitely something we need to address so I'm going to keep this ticket around.

**Comment by dwieeb** [comment]
With how the code is currently bootstrapped (basically everything kicking off when the module loads and no dependencies injected), there's no way right now to inject a different logger before the logger is used. I am also seeing my karma log sprinkled with log messages. I cannot address this without refactoring significant portions of the client, so this may need to sit for a while longer.

**Comment by dwieeb** [comment]
Check out that commit ☝️ 

For now we'll expose the `silent` option. With Angular 1 I know it's possible to override services, but we don't use the Angular 1 dependency injection framework internally, so it wouldn't override the logger instance.
