### ISSUE TITLE
Device receives notification, but onNotification callback does not fire

### ISSUE THREAD

**Issue by tannerlinsley** [driftyco/ionic-platform-web-client#55]
Xcode shows that the app is recieving a push notification successfully, but the callback defined in the `onNotification` property of the config never gets fired.  Any ideas?

**Comment by ericb** [comment]
Are you making sure to call `register` each time the app runs?

**Comment by tannerlinsley** [comment]
Yeah I am. Im pretty sure the device is getting the notes. They show in the
x code console. They just never make it down to the javascript callback

**Comment by ericb** [comment]
Hrm, that would seem to indicate that the plugin has not started listening for the notifications. Can you instantiate a new Ionic.Push instance while the app is running (using safari console) and call register, and then send a notification.

**Comment by tannerlinsley** [comment]
Yeah I'll give that a try. You just made me remember. Does ionic.push need
to be instantiated within a platform.ready block?

**Comment by ericb** [comment]
It can be, but I don't believe it's a requirement (I'd have to dig through some code to verify though).

**Comment by tannerlinsley** [comment]
Okay. I'll try it in the console and let you know.

**Comment by tannerlinsley** [comment]
It registered fine, got the token, and sent the push.

Xcode logs: 
```
didReceiveNotification with fetchCompletionHandler
Notification received
Push Plugin key: alert
```

But the notification still never got to the `onNotification` handler. :(

**Comment by dasgib** [comment]
Are you really, really sure that you call $ionicPush.register() every time the app is being loaded (for example within $ionicPlatform.ready()), not just once?

**Comment by tannerlinsley** [comment]
I'm positive.  The entire app is wrapped in a Platform.ready() callback, (I can confirm that many other services that require the platform to be ready are working properly).  The `register` method is called every single time a user is authed (any time the app launches)

```javascript
// Push Service excerpt

window.Ionic.io()
  var push = new window.Ionic.Push({
    onNotification: notify,
    pluginConfig: {
      ios: {
        alert: true,
        badge: true,
        sound: true
      },
      android: {
        sound: true,
        vibrate: true,
        forceShow: true,
        iconColor: "#601dc2"
      },
    }
  })

function register() {
    if (window.localStorage.emulator) {
      return $q.when()
    }
    var d = $q.defer()
    push.register(function(token) {
      service.token = token.token
      d.resolve(service.token)
    })
    return d.promise
  }
```


```javascript
// User Service excerpt

API.get('user')
  .then(function(res) {
    service.me = res.data
    registerPushToken()
    return service.me
  })

function registerPushToken() {
  Push.register()
    .then(function(token) {
      var found = _.indexOf(service.me.pushTokens, token) > -1
      if(!found){
        service.me.pushTokens.push(token)
        save(service.me)
          .then(function(){
            window.localStorage.pushToken = token
          })
      }
    })

  }

```

**Comment by boyfunky** [comment]
so u mean each time a notification is sent, the push.register() must be called?

**Comment by boyfunky** [comment]
so basically i have to do this in my apps.js? 

@brace110: tht didnt work even after changing to notification. 
I am using Ionic.Push  and in my app.js after my ionicPlatform.ready, i changed to this but it still doesnt catch it 

```
var io = Ionic.io();
var push = new Ionic.Push({
        "onNotification": function(notification) {
          console.log("NOTIFICATION RECEIVED")
        },
        "onRegister": function(notification){
      
        }
});
```
Do i need to do this as well push.register() ?? @ericb @tannerlinsley @dasgib 

What is the reason why i need to call the register() function always?

**Comment by Fuiste** [comment]
@boyfunky it's best practice to call `push.register()` on each start of your app, yes.  Here's a run block from a push app I just made as an example:

```
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    var push = new Ionic.Push({
      "debug": true
    });
    push.register(function(token) {
      console.log("Device token:",token.token);
    });
  });
})
```

Register ensures the validity of push tokens, and will (in almost all cases) **not** result in new tokens being generated, as these are built on a per-app, per-device level.

Anyways, back to @tannerlinsley's original question.  How are you instantiating the push service (not the register, the `new Ionic.Push()`)?  Is this happening on _every_ start of the app in addition to the registration?  I'm wondering if your `onNotification` function is undefined in some cases (before login, or when the app has been col-started), and as such isn't getting run.

**Comment by Shinzah** [comment]
I got the same issue here, on Android (not tried on iOS).
I register successfully and i receive notificaitons when the app is closed.
But when the app is in foreground, the onNotification callback is never called.

Other problem, when the app is closed and i click on the notification, it doesn't open the app .... strange

**Comment by ericb** [comment]
@Shinzah What version of the push plugin / ionic-platform-web-client are you using. Also do you have a notification id I can take a look at to see what properties you've used?

**Comment by Shinzah** [comment]
Cordova plugin version:
```phonegap-plugin-push 1.6.0 "PushPlugin"```
ionic-plateform-web-client version:
```ionic-platform-web-client#0.6.0```
And a notificaiton uuid :
```c1d08826-288b-462a-8fd6-2f8c13b7e17e```

**Comment by ericb** [comment]
@Shinzah The messages have sent successfully, but I noticed you are setting some icon attributes -- can you attempt to send a basic message "only message or title and message" with no other options. I'd like to see if the configuration is related or not.

**Comment by Shinzah** [comment]
I've tried, but unsuccessfull :(
Notification uuid:
``` 70092e0d-7d96-4400-a569-06e58cefea06 ```

**Comment by ericb** [comment]
@Shinzah Same thing, the message is sent successfully. I suspect there is a misconfiguration in your app code somewhere. When you register, is it dumping the same token each time? How are you verifying the onNotification handler is not called?

**Comment by Shinzah** [comment]
I've checked the logcat, and there is nothing throwed.
Again, the code i use, is the same which i was using with the alpha version of ionic push... :(
The token is still the same on each registration.
I've put an alert on the "onNotification" callback method, and it never popout...

**Comment by ericb** [comment]
If there is nothing in logcat, then your device is not even receiving the notification, which might indicate an entirely different set of problems. Either plugin has not been registered, gcm is delayed (unlikely), or your app is erroring/misconfigured. 

I'd try starting a new ionic project from scratch, and adding push into that app following the setup guides in the push docs. If that has similar problems we can debug further.

**Comment by Shinzah** [comment]
Hmm, i think i'm not clear about my problem.

When the application is in foreground, i receive a notification in android statusbar, but there is no "noNotification" callback called, and when i click on the notification in android statusbar, nothing append.

When the application is in background, i receive a notification in android statusbar, and if i click on it, nothing append.

So, the GCM and the registration work fine, it's "just" the notification handling by the app which is not working, and the "click" on the notification ...

**Comment by ericb** [comment]
@Shinzah And you're sure you've called the push `register` on app start? What happens if you remove the plugin and install a previous version like 1.5.2

**Comment by Shinzah** [comment]
Yes, i call register on application start. I've put an alert and the token is still the same.
I've already tried to downgrade phonegap-plugin-push to 1.5.2, but it doesn't resolve the problem :(

**Comment by ericb** [comment]
@Shinzah In that case i'm not sure what else to try -- if logcat does not show any incoming messages but your device is showing a notification in the shade, i'm totally perplexed.

**Comment by Shinzah** [comment]
Well, i've just tried something, and it works fine ..
I've remove ionic-platform-web-client (ionicUser & ionicPush), and directly send my push creation to GCM, and all work fine :(

**Comment by danielslz** [comment]
I got the same issue.

**Comment by Fuiste** [comment]
@Shinzah can you confirm this issue is still occurring with the latest platform web client?

We've updated some things on the backend to address the issue.

**Comment by Fuiste** [comment]
Update: After testing, we're marking this issue fixed as far as we can tell.

Let us know if it crops up again.

**Comment by salem-k** [comment]
i have the same issu, but i havn't use ionic-platform-web-client or ionicUser & ionicPush: 
this is all plugins i have used :
com.danielcwilson.plugins.googleanalytics 0.6.1 "Google Universal Analytics Plugin"
com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-crosswalk-webview 1.7.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-globalization 1.0.0 "Globalization"
cordova-plugin-inappbrowser 1.1.0 "InAppBrowser"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-whitelist 1.2.0 "Whitelist"
de.appplant.cordova.plugin.email-composer 0.8.3dev "EmailComposer"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 1.0.8 "Keyboard"
nl.x-services.plugins.socialsharing 4.3.19 "SocialSharing"
org.apache.cordova.statusbar 0.1.10 "StatusBar"
org.pushandplay.cordova.apprate 1.1.7 "AppRate"


Thanks for help

**Comment by ishamrozeraza** [comment]
So, few days back my notifications were working fine.. and now they dont seem to receive under 'onNotification' callback function. When i send the curl request from terminal or from postman the notification or from my notification service (server /node ).

`exports.sendNotification = function(tokensArr, title, message, payload){

	var deferred = q.defer();

	console.log("tokensArr:", tokensArr);
	
	var notification = {
		"tokens": tokensArr,
		"profile": "gcm",
		"notification": {
			"title": title,
			"message": message,
			"payload": payload
		}
	};

	var options = {
	    url: 'https://api.ionic.io/push/notifications', 	    
	    method: 'POST',
	    headers: {
	        'Content-Type' : 'application/json',
	        "Authorization" : "Bearer " + config.ionic.apiToken
	    },
	    body: JSON.stringify(notification)
	};

	request(options, function(error, response, body){
	    if(error) {
	        console.log(error);
	        deferred.reject(error);
	    } else {
	        console.log(response.statusCode, body);
	        deferred.resolve(response);
	    }
	});

	return deferred.promise;
};
`

The success callback does return  status 201 with data but 'onNotification' has stopped working ,(all of a sudden..) 
any help ?

**Comment by ishamrozeraza** [comment]
ok so in my case, it was the 'payload' ! , may be the objects i was sending got much bigger than they were earlier. i reduced the payload , and i was able to see notifications on device !
