### ISSUE TITLE
iOS notifications on ionic says notification success but message not received on device

### ISSUE THREAD

**Issue by boyfunky** [driftyco/ionic-platform-web-client#57]
I am using the ionic service after setting up everything the way it shud be and all, whenever i send a message using the ionic service, one time push notification, i get this message 

> {"errors":[],"message_id":"c27b776ad2b211e5b1cf9e127b0bee5b","result":"queued"}

when i check the status of d message i get this 

> {"errors":[],"ios":{"failure_reason":"","success":true,"sent":1},"status":"Sent","android":{"failure_reason":"","success":false,"sent":0},"app_id":"f3ed159b"}

But i never receive the message on the device

What could be the problem

**Comment by ericb** [comment]
@boyfunky Make sure you have called register() each time the app has opened. Also, if the app is open when the message is received, your callback will get the message but the device will not show a notification in the shade area.

**Comment by boyfunky** [comment]
got it thanks @ericb

**Comment by Fuiste** [comment]
If I gather correctly, it looks like this issue has been resolved.  

I'm going to close this one for now, but feel free to let us know and reopen if the problem persists.

**Comment by arilishu** [comment]
@ericb what's the meaning of register()?
Can you show us that code please?

When i use the ionic serve, only when the server starts i can see:
push.register(function(token) {
      console.logtoken.token );
    });


But the next reloads the method is not invoked

**Comment by mardikacom** [comment]
I experience the same problem when trying to use ionic push notification test. It said queued
I added this script to the app.js 
`var push = new Ionic.Push({
      "debug" : true  
    });
    push.register(function(token){
      console.log("device token : ",token.token);      
    });`
Cordova CLI : 6.0.0
Ionic Version : 1.2.4
Ionic CLI Version : 1.7.14
Ionic App Lib Version : 0.7.0
OS : WIndows 7 SP 1
Node Version : v4.3.0

**Comment by saikat1529** [comment]
Hello, 
I am also facing the same problem. Did anyone find the solution of that? By the way i am adding the following command for plugin "cordova plugin add https://github.com/phonegap-build/PushPlugin.git"
