### ISSUE TITLE
Not registering tokens in browser

### ISSUE THREAD

**Issue by nickfrandsen** [driftyco/ionic-platform-web-client#58]
I followed the [quick start guide](http://docs.ionic.io/docs/push-quick-start) on ionic but I was not returned any tokens. I am testing in the browser and have set dev_push true. I did a little digging through the source code and found that onReady was never called because this._isReady was false. I can fix it by explicitly calling init() on the push object but it doesnt say to do this in the docs. Is it a bug? Or am I doing something wrong?

```
      Ionic.io();

      var push = new Ionic.Push({
        "debug": true,
        "onNotification": function(notification) {
          var payload = notification.payload;
          console.log(notification, payload);
        },
        "onRegister": function(data) {
          console.log(data.token);
        }
      });
      //WORKS ONLY IF I ADD INIT() AS BELOW
      push.init();
      push.register(function(token) {
        // Log out your device token (Save this!)
        alert("Got Token:"+token.token);
      });
```

Thanks for your help!

**Comment by ericb** [comment]
Are you running 'emulation' mode in the browser? If so, the init never fires as we think it's a mobile device  and are waiting on some other initialization to occur (which never will in this case).

**Comment by nickfrandsen** [comment]
Thanks Eric! That is exactly whats going on (facepalm). I'll close this issue now. Cheers
