### ISSUE TITLE
User's image property is not set when the user is loaded from local storage

### ISSUE THREAD

**Issue by perttuim** [driftyco/ionic-platform-web-client#59]
It seems the user's image property is not set when the user is loaded from local storage with Ionic.User.current().

I forked the repo and made a quick change to fix it. I'm not sure if my solution is the correct one but it works for now. You might want to investigate more.

**Comment by ericb** [comment]
Did you mean to submit a pull request?

**Comment by perttuim** [comment]
Pull request submitted.
