### ISSUE TITLE
onNotification gets a null text

### ISSUE THREAD

**Issue by ivanarrizabalaga** [driftyco/ionic-platform-web-client#6]
In a code like this:

```javascript
			$ionicPush.init({
				"onNotification": function (notification) {
					var payload = notification.payload;
					console.log(notification, payload);
				},
```

The **notification** object is a PushMessage with **text:null** where it should be the received  message.

It looks like the problem is that the object from the plugin is wrapped into a PushMessage object (which is  just fine) but this PushMessage **is wrapped again** into another PushMessage while preparing the notificationCallback.

![notificationcallback_error](https://cloud.githubusercontent.com/assets/4146319/10391751/55b78e60-6e81-11e5-8ab7-cf048fe69165.png)

I think this shouldnt be done since you're already dealing with a PushMessage and the function **fromPluginJSON** is not prepared to clone a PushMessage (the property is **text** instead of **message**).

**Comment by chriswitko** [comment]
+1
