### ISSUE TITLE
Ionic Push: notification payload badge sound = null and count = null

### ISSUE THREAD

**Issue by stewartmccoy** [driftyco/ionic-platform-web-client#61]
I'm working on getting Ionic Push set up for iOS (version 9.2.1 running on iPhone 5). I can successfully trigger one-time notifications from the ionic.io dashboard and receive them on a build on my physical device. However, I've had lots of difficulty getting badge and sound to work. 

For background: I'm following the instructions on [Push from Scratch](http://docs.ionic.io/docs/push-from-scratch). I'm building for iOS, so I followed all the instructions on [iOS Setup](http://docs.ionic.io/v1.0/docs/push-ios-setup).

The init function I'm using looks like this:

```
$ionicPush.init({
      "debug": true,
      "onNotification": function(notification) {
        console.log(notification.text);
        console.dir(notification);
        $state.go('tab.chat-detail', {chatId: '1'});
        return true;
      },
      "onRegister": function(data) {
        alert(data.token);
      },
      "pluginConfig": {
        "ios": {
          alert: "true",
          badge: "true",
          sound: "true"
        }
      }
    });

    $ionicPush.register();

```

From the dashboard, my curl request looks like this:

```
curl -u my-private-key: -H "Content-Type: application/json" -H "X-Ionic-Application-Id: 2bc24b0e" 
https://push.ionic.io/api/v1/push -d '{"tokens": ["my-device-token"],"production": false, "notification":{ 
"alert":"hello nick hope canada is nice", "title": "hey dude", "android": {"payload": {"sound": 
"boring.wav","badge": "true"}}, "ios": {"payload": {"sound": "boring.wav","badge": "true"}}}}'
```

I've tried `"sound": "default"` and `"sound": "true"`, but neither work. I've also tried a custom sound, such as `"sound": "boring.wav"`. I put the .wav file in the root www/. I also tried change the relative path in the payload to `"sound": "../boring.wav" because I was assuming the sound file is relative to js/app.js.

Screenshot of my sound file in www/:

<img width="632" alt="screen shot 2016-02-21 at 8 19 50 pm" src="https://cloud.githubusercontent.com/assets/1393022/13209426/8b05293a-d8d8-11e5-82e1-dba822e1332b.png">

Overall, the REST call seems fine and there are no errors. A friend of mine who was pairing with me on this issue suggested: "It's converting the JSON payload to the notification parameter in the "onNotification" that is getting screwed up."

My friend writes further:

> There seems to be a disconnect in the PushMessage _raw property and the PushMessage.processRaw method. The count appears to be in additionalData, not at the same level as title, see https://github.com/driftyco/ionic-platform-web-client/blob/master/src/push/push-message.js#L51.

I spoke with somebody on the Ionic Platform services team via email and he said to use `badge` in my payload (see below), but you'll notice that the code above specifies `count`:

```
curl -u my-private-key: -H "Content-Type: application/json" -H "X-Ionic-Application-Id: my-app-id" 
https://push.ionic.io/api/v1/push -d '{"tokens": ["my","device","tokens"],"production": false, "notification":{ 
"alert":"I'm a push", "title": "Hello world", "android": {"payload": {"badge": 4,"sound": "hello.wav"}}, "ios": 
{"payload": {"badge": 4,"sound": "hello.wav"}}}}'
```

When I `console.dir` the object in the Safari Inspector for the device, I see this:

<img width="1018" alt="screen shot 2016-02-21 at 6 31 44 pm" src="https://cloud.githubusercontent.com/assets/1393022/13209267/d8becab6-d8d6-11e5-9326-d89e86540f35.png">

Notice that count and sound are null.

plugin info:

```
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-splashscreen 3.2.0 "Splashscreen"
cordova-plugin-statusbar 2.1.1 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
ionic-plugin-keyboard 1.0.8 "Keyboard"
phonegap-plugin-push 1.5.3 "PushPlugin"
```

package.json:

```
{
 "name": "barkit",
 "version": "1.1.1",
 "description": "barkit: An Ionic project",
 "dependencies": {
   "gulp": "^3.5.6",
   "gulp-sass": "^2.0.4",
   "gulp-concat": "^2.2.0",
   "gulp-minify-css": "^0.3.0",
   "gulp-rename": "^1.2.0"
 },
 "devDependencies": {
   "bower": "^1.3.3",
   "gulp-util": "^2.2.14",
   "shelljs": "^0.3.0"
 },
 "cordovaPlugins": [
   "cordova-plugin-device",
   "cordova-plugin-console",
   "cordova-plugin-whitelist",
   "cordova-plugin-splashscreen",
   "cordova-plugin-statusbar",
   "ionic-plugin-keyboard",
   "phonegap-plugin-push"
 ],
 "cordovaPlatforms": [
   "ios"
 ]
}

```

Here's my app.js code: 

```
// Ionic Starter App

// angular.module is a global place for creating, registering and retrieving Angular modules
// 'starter' is the name of this angular module example (also set in a <body> attribute in index.html)
// the 2nd parameter is an array of 'requires'
// 'starter.services' is found in services.js
// 'starter.controllers' is found in controllers.js
angular.module('starter', ['ionic','ionic.service.core', 'starter.controllers', 'starter.services', 'ionic.service.push'])

.run(function($ionicPlatform, $state, $ionicPush) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);

    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }

    $ionicPush.init({
      "debug": true,
      "onNotification": function(notification) {
        console.log(notification.text);
        console.dir(notification);
        $state.go('tab.chat-detail', {chatId: '1'});
        return true;
      },
      "onRegister": function(data) {
        alert(data.token);
      },
      "pluginConfig": {
        "ios": {
          alert: "true",
          badge: "true",
          sound: "true"
        }
      }
    });

    $ionicPush.register();
  });
})

.config(function($stateProvider, $urlRouterProvider) {

  // Ionic uses AngularUI Router which uses the concept of states
  // Learn more here: https://github.com/angular-ui/ui-router
  // Set up the various states which the app can be in.
  // Each state's controller can be found in controllers.js
  $stateProvider

  // setup an abstract state for the tabs directive
    .state('tab', {
    url: '/tab',
    abstract: true,
    templateUrl: 'templates/tabs.html'
  })

  // Each tab has its own nav history stack:

  .state('tab.dash', {
    url: '/dash',
    views: {
      'tab-dash': {
        templateUrl: 'templates/tab-dash.html',
        controller: 'DashCtrl'
      }
    }
  })

  .state('tab.chats', {
      url: '/chats',
      views: {
        'tab-chats': {
          templateUrl: 'templates/tab-chats.html',
          controller: 'ChatsCtrl'
        }
      }
    })
    .state('tab.chat-detail', {
      url: '/chats/:chatId',
      views: {
        'tab-chats': {
          templateUrl: 'templates/chat-detail.html',
          controller: 'ChatDetailCtrl'
        }
      }
    })

  .state('tab.account', {
    url: '/account',
    views: {
      'tab-account': {
        templateUrl: 'templates/tab-account.html',
        controller: 'AccountCtrl'
      }
    }
  });

  // if none of the above states are matched, use this as the fallback
  $urlRouterProvider.otherwise('/tab/dash');

});
```

Please reference this issue as it might be related: [onNotification gets a null text](https://github.com/driftyco/ionic-platform-web-client/issues/6)

**Comment by stewartmccoy** [comment]
I had previously been advised format my curl as below, with badge and sound specified inside the payload. Turns out that they need to go as a child of "ios" rather than inside the payload. Here's an example of the badly formatted request:

```
curl -u my-private-key: -H "Content-Type: application/json" -H "X-Ionic-Application-Id: my-app-id" https://push.ionic.io/api/v1/push -d '{"tokens": ["my","device","tokens"],"production": false, "notification":{ "alert":"I'm a push", "title": "Hello world", "android": {"payload": {"badge": 4,"sound": "default"}}, "ios": {"payload": {"badge": 4,"sound": "default"}}}}'
```

And here is the correctly formatted curl request that results in badge and sound working properly:

```
curl -u abfc6bf427fe53c4419685ec824cd34c59e2dba7734e1158: -H "Co https://push.ionic.io/api/v1/push -d '{"tokens":["d59764af2f9c36bd4d6252c0f80a1553a4d18ce51fefd83bbf32fb8468d38de8"],"notification":{"alert":"Hello World oh man!","ios":{"badge":1,"sound":"default"}}}'
```

So, there we go...ha.

**Comment by leizard** [comment]
So, putting the file in the www folder works ? For Android, I put the sound file in platform/android/res/raw as pointed in [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound) but I still get the default sound.

**Comment by animista01** [comment]
@leizard In iOS you need to put the sound file on your "Resources" directory in Xcode and in Ionic.io json: { "badge" => 1, "sound" => "www/mp3/savvyNotification.wav" }
For Android you need to create a folder inside the "res" directory and called it "raw" and put there the sound file, and in Ionic.io json: {"badge" => 1, "sound" => "notification"} notice that it doesn't need the extension name.

**Comment by leizard** [comment]
Hey @animista01, thank you for your reply. In Android, I just emitted the file extension in my JSON to make it work. `sound: bell` instead of `sound: bell.mp3` and every thing work like a charm. I will try your recommendation and response asap.

**Comment by kuzun9x** [comment]
Hi,
With my app, when sending curl, I don't add 'badge'. In android mobile, count notification is still show on icon app, but IOS don't.
When I add 'badge': true in curl, in IOS, icon always show 1 on icon app although mobile received 3 notification. In Android, always run correctly.
If i set number for 'badge', in icon app will always show this number on icon app.
What is solution to fix ios correct?
Thanks!
