### ISSUE TITLE
Receive Notifications in background on Android 

### ISSUE THREAD

**Issue by boyfunky** [driftyco/ionic-platform-web-client#62]
I am trying to receive push notifications when my app is in the background. Currently my code looks like this 

in my app.js
```
var push = new Ionic.Push({
      "onNotification": function(notification) {
        // send notification_read true to server
        console.log("NOTIFICATION RECEIVED")
        alert("SUCCESSFULLY RECEIVED NOTIFICATION");
      },
      "onRegister": function() {

      }
    });
    push.register();
```
Currently when my app is in the foreground, and a notification is sent, the onNotification event fires but when my app is in the background, it doesnt fire. 

I have tried doing this also 

```
$rootScope.$on('$cordovaPush:notificationReceived', function(event, notification) {
      console.log("ON NOTIFICATION")
    })
```

and also tried this as well 
```
push.on('notification', function(notification) {
  console.log("on notification")
})
```

and this as well because i am using cordova-plugin-push

```
var pushPlugin = window.PushPlugin;

pushPlugin.on('notification', function(notification) {
  console.log("on notification")
})
```
but it also all doesnt work to catch the Notification event.
On all these scenarios, i get the error message push.on('notification') is not a function. 

Is there anythg im doing wrongly?

**Comment by ericb** [comment]
Please see the explanation I posted on your push plugin repo issue.
