### ISSUE TITLE
Once a user is deleted, cannot create a new user with the same userId

### ISSUE THREAD

**Issue by razmik** [driftyco/ionic-platform-web-client#64]
Reproduce steps:

1. Create a new user in ionic io.
`Ionic.io();
var user = Ionic.User.current();
user.id = 'myCustomId1';
user.save();`

2. Delete the user from the app.
`Ionic.User.current().delete();`

3. Create the user with same user id.
`Ionic.io();
var user = Ionic.User.current();
user.id = 'myCustomId1';
user.save();`

This gives success callback in `user.save()`, but user is not created on https://apps.ionic.io/app/XXXXXX/users/list

**Comment by ericb** [comment]
With the beta update, users can no longer be assigned user ids.
