### ISSUE TITLE
Error: Cannot find plugin.xml for plugin 'package'.

### ISSUE THREAD

**Issue by ericmasiello** [driftyco/ionic-platform-web-client#65]
Upon executing this:

`ionic plugin add ionic-platform-web-client`

I get this:

`Error: Cannot find plugin.xml for plugin 'package'. Please try adding it again.`

Here's my Ionic info

Your system information:

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.3 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by Fuiste** [comment]
The `ionic-platform-web-client` isn't a Cordova plugin, and as such should be installed with

```
ionic add ionic-platform-web-client
```

rather than using the `plugin` keyword.

**Comment by ericmasiello** [comment]
right sorry. But when when I run `ionic state reset`

it triggers a call to `cordova plugin add ionic-platform-web-client` which results in

```
/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
                                                           ^
Error executing "cordova plugin add ionic-platform-web-client":
Fetching plugin "ionic-platform-web-client@git@github.com:driftyco/ionic-platform-web-client.git" via npm
Error: Cannot find plugin.xml for plugin 'package'. Please try adding it again.
```

**Comment by ericmasiello** [comment]
Or is it not a cordova plugin?

**Comment by Fuiste** [comment]
@ericmasiello it's not a Cordova plugin.

Looks like you've got a reference to the platform web client in the wrong place in your `package.json`, causing it to get reinstalled as a plugin on `ionic state reset`

**Comment by ericmasiello** [comment]
Ah. you're right. So where does Ionic app actually store that this was installed?

**Comment by ericmasiello** [comment]
nevermind. im a dummy. bower.json. sorry!

**Comment by Fuiste** [comment]
No worries! Glad to yelp.

**Comment by renjithvk** [comment]
### SOLVED

It's just a **permission issue**. Please set current user as the owner of the project files

`$ sudo chown -R $(whoami) project-directory`
