### ISSUE TITLE
Uncaught ReferenceError: Ionic is not defined

### ISSUE THREAD

**Issue by ericmasiello** [driftyco/ionic-platform-web-client#66]
I followed the directions
```
ionic add ionic-platform-web-client
ionic plugin add phonegap-plugin-push
ionic io init
ionic config set dev_push true
```

Then inside my `$ionicPlatform.ready` I'm running the following sample code from the docs:

```
var push = new Ionic.Push({
    "debug": true
 });

push.register(function(token) {
    console.log("Device token:",token.token);
});
```
However, no matter what I do, I seem to get the same error: `Uncaught ReferenceError: Ionic is not defined(…)`

Here's my ionic info

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.3 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

Where does `Ionic` get defined? I'm using a custom build system that builds all my src files in a separate directory, concatenates them and then puts everything into the www. directory. 

Any help?

**Comment by ericb** [comment]
The custom build process is the issue here. We [modify](http://docs.ionic.io/v2.0.0-beta/docs/io-service-modules#section-modifications) the platform client currently to house the config for your app. We understand this was a mistake and have an [open discussion](https://github.com/driftyco/ionic-platform-web-client/issues/41) going on how we will address this in the future.

**Comment by ericmasiello** [comment]
Thanks! 

It'd helpful if there was a resource that gave more detailed instructions regarding what changes in each of those files and how one might manually replicate them in their own applications. Is there anything out there like this you are aware of?

**Comment by ericb** [comment]
We are just pushing the JSON object from .io-config.json into a specific area of the client code. It's something like "IONIC_IO_CONFIG_START";"IONIC_IO_CONFIG_END"; 

That happens in both the minified and non-minified files of the `dist` folder.

It may be easier for you to just update your custom build process to temporarily place the web client in the expected directory, run `ionic config build` and then move back to your proper location before running the rest of your build.

**Comment by ericmasiello** [comment]
Okay. I found the string you're referring to. Its 

`IONIC_SETTINGS_STRING_START` and `IONIC_SETTINGS_STRING_END`.

Just so I'm clear, when you run `ionic config build`, it goes and looks for the files:
`www/lib/ionic-platform-web-client/dist/ionic.io.bundle.js`
`www/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js`

And then it jams in between those two strings the values defined inside of `.io-config.json`. Is that mostly right?

Can you point me to the source code for the `ionic config build` method?

**Comment by Fuiste** [comment]
@ericmasiello here you go https://github.com/driftyco/ionic-app-lib/blob/master/lib/io-config.js

**Comment by warner-pinz** [comment]
@ionic folks. Does this work with Ionic 2? I'm getting the same error with Ionic 2. It would really help us ionic 2 users here if you could shed some light. I'm having the same error integrating push notification.
Thanks

**Comment by Shadowstep33** [comment]
Yes, this is a pretty big roadblock for me as well. Ionic.Auth is obviously completely inaccessible; how are we to resolve this on a per app basis?
