### ISSUE TITLE
v0.4.0 - User custom details

### ISSUE THREAD

**Issue by Shinzah** [driftyco/ionic-platform-web-client#67]
With the version 0.4.0, the user custom details is not posted and saved when signup.
They are not in the POST request, and not in ionic.io backoffice.

In sources, only app_id, email and password are posted :

```
new _coreRequest.APIRequest({
        'uri': authAPIEndpoints.signup(),
        'method': 'POST',
        'json': {
          'app_id': settings.get('app_id'),
          'email': data.email,
          'password': data.password
        }
```

**Comment by ericb** [comment]
Yes, it looks like we forgot to anticipate that int he web client -- i will put that on our list of updates. Thank you!
