### ISSUE TITLE
v0.4.0 - Push with new API

### ISSUE THREAD

**Issue by Shinzah** [driftyco/ionic-platform-web-client#68]
I've upgraded my app with the version 0.4.0.
User are correctly saved in Ionic.io, and token too (a POST is correctly done when i use ionicPush.register()).

But when i tried to send a notification to the previously saved token, API Server enqueued my request, and ... i never receive the notification.

`      "status": "open",
      "created": "2016-03-03T15:09:40.933254+00:00",
      "uuid": "xxxxxxxx-55b5-42f0-a8d8-90912053bf16",
      "state": "enqueued"`

When i'm looking for the notification status, the "status" field is "locked" :

`    "status": "locked",
    "created": "2016-03-03T14:46:07.860411+00:00",
    "uuid": "xxxxxx-55b5-42f0-a8d8-90912053bf16",
    "state": "enqueued"
  }`

What does that mean ?

I don't receive any errors, but no notification received on my device ... how to debug and found the problem ?

Thank you for your help

**Comment by Shinzah** [comment]
Please not that it work in "dev_push: true" in a browser.

**Comment by Fuiste** [comment]
This is a platform issue outside the scope of the web client, so I'm moving it to https://github.com/driftyco/ionic-platform-issues

**Comment by Fuiste** [comment]
This issue was moved to driftyco/ionic-platform-issues#41
