### ISSUE TITLE
Ionic-platform-web-client and phonegap-push-plugin don't play nicely.

### ISSUE THREAD

**Issue by wbhob** [driftyco/ionic-platform-web-client#69]
I developed my app for the most part in ionic serve because I only get a white screen when I emulate from the command line. Emulating from xcode works fine, and so does a device.

**Comment by ericb** [comment]
There is not enough information here to diagnose your issue. If you can provide more information such as the javascript or xcode logs, dumps from `ionic config info` and `ionic info` then I can potentially reopen the issue.
