### ISSUE TITLE
ios9 push notifications not working

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-platform-web-client#7]
other versions receive push, IOS9 does not. this is critical for our business...

**Comment by ericb** [comment]
What do you mean other versions? Do you get any errors in your safari console logs or XCode logs? Are you able to register and receive a token?

**Comment by sagivf** [comment]
Thanks for the quick response!

It works in dev_mode and it works in production with devices that have IOS8.
It just refuses to work with my IOS9 device...
When I use ionic.io "once time push" It tells me the push was delivered to IOS but I don't get it on my device...

**Comment by ericb** [comment]
Can you attempt to send one now using curl or the one-time notification tool and give me the message id.

**Comment by sagivf** [comment]
I got it working with a lot of vodo...
One thing that was I great source of confusion was that I did `push.unregister` on user logout.
This killed push and I had to erase the app from my phone to get it back.

The user and push api are not clear - theres `push.addTokenToUser` but no `push.removeTokenToUser`, I ended up implementing it myself by looking at the user source code.

Would you like a pull request? :)

**Comment by ericb** [comment]
`addTokenToUser` is a convenience method of the push class, but you can add remove tokens to users with the user object directly with `user.addPushToken(token)` and `user.removePushToken(token)`

When you say push.unregister killed your app, what do you mean exactly? Did you just stop receiving notifications, or did you get an app error of some sort?

**Comment by sagivf** [comment]
Thanks for all the help, got it to work (on IOS9 ,IOS8 isn't working).

With `push.unregister` there's no error, but the notifications stop working, the token isn't deleted and re-registering doesn't help - nor does re-instantiaing the push service.
So what is it for? what usecase?

if theres `push.addTokenToUser(user);` why no `push.removeTokenToUser(user);`

I think you need to update the docs - user is completely undocumented and push is confusing.
The push documentation only mentions `push.addTokenToUser(user)`  and  `push.unregister`  whichc don't seem to be enough to get a login/logout flow to work.

**Comment by gravity-addiction** [comment]
I've played with the push.unregister and found that i have to completely delete the app and reinstall it for me to get a new token. The register() function will continue to retrieve the unregistered token.

iOS troubles usually come from making sure my app push is in the correct mode, otherwise the certificates wont line up (ionic push --production-mode=   and   ionic config set dev_push)

**Comment by ericb** [comment]
So a similar issue was brought up by another user, this appears to be an issue on our end where we need to mark a previously invalid token, back to a valid state. I believe iOS tokens are only generated once per app build or very infrequently, and as such, unregister/register will more than likely use the same token.

We're working on a fix now.

**Comment by sagivf** [comment]
@ericb No prob, but please take my comments into consideration. Your push service is very elegant and robust. But if users can't get it to work that all goes out the window...

**Comment by ericb** [comment]
@sagivf Which part specifically?

**Comment by gravity-addiction** [comment]
@sagivf it's working for me, android setup was easy. ios setup on the other hand, not so much. all the certificates, provisioning profiles in xcode have to line up with the ionic modes and uploaded certificates. believe me when I got it working I was afraid to change between the dev and production profiles.

**Comment by sagivf** [comment]
@gravity-addiction I'm with you, to much vodo :)
@ericb Regarding the documentation/missing-api.

**Comment by sagivf** [comment]
If you can point me in the right direction would be glad to add a pull request

**Comment by gravity-addiction** [comment]
@sagivf user information has been separated from the push services. You can remove a token from the user. Looking thru the new version I see a user.removePushToken(token) function. Ionic users are supposed to be pretty plain and really universal. A push.removeTokenFromUser(user); function just hasn't been written yet.

**Comment by eseca** [comment]
Hi. We have encounter this same issue. Can you guys tell us how you made it to work? Any help would be appreciated. Thanks.
