### ISSUE TITLE
500 error on Ionic.Auth.login

### ISSUE THREAD

**Issue by robtaireeo** [driftyco/ionic-platform-web-client#71]
Getting a 500 internal error trying to use Ionic auth login with google.

This happened on both 0.5.2 and 0.6.0.

Code: 
`
        try {
            Ionic.Auth.login('google', { 'remember': true })
                .then(function(success) {
                    console.info('success: ', success);
                }, function(failure) {
                    console.warn('failure: ', failure);
                });
            console.info('after login call');
        }
        catch (err) {
            console.error('error with google sign in', err);
        }
`

screenshot in emulator:
[screenshot](http://i.imgur.com/gwJc67o.png)

**Comment by robtaireeo** [comment]
Missed 1 step in the setup: enabling Google+ API.

**Comment by dwieeb** [comment]
We will be improving the error handling for third party authentication next week.
