### ISSUE TITLE
Problem while installing to Ionic 2 project

### ISSUE THREAD

**Issue by fedorinoGore** [driftyco/ionic-platform-web-client#72]
Hello.
Recently wanted to try Ionic Platform user service.
Problems started from the very beginning.
After 
`$ ionic add ionic-platform-web-client `
I got an error:
```
ERROR:  Error: ENOENT: no such file or directory, open './www/js/app.js'
    at Error (native)
Is your app declaration contained in 'app.js'?
Adding component to index.html
Saved dev_push, writing to ionic.io.bundle.min.js...
```
Component was installed in **/bower_components/** folder.
But in **index.html** I could see:
`<script src="../lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js"></script>`
Which points to path common for Ionic 1.
As expected `ionic serve` breaks and cannot find a file on this path...
I could see a creepy solution here: https://forum.ionicframework.com/t/push-notifications-with-ionic2/40269/2 as people experiencing same troubles with ionic-platform-web-client, but I'm really concerned that breaking in source code may interfere with upcoming releases and will cause project to break in the future...

**Comment by ericb** [comment]
We don't have any official Ionic 2 support just yet (though I'm hoping to dive into that this week). We also have an [open discussion](https://github.com/driftyco/ionic-platform-web-client/issues/41) regarding the platform configuration.

We will absolutely be changing the way we handle the platform configuration and Ionic 2 support should be coming soon as well.
