### ISSUE TITLE
Provide an alternative way of setting config

### ISSUE THREAD

**Issue by mattlewis92** [driftyco/ionic-platform-web-client#74]
In our app we gitignore any installed files installed with bower (and use a non default directory) so writing the config inline to the `ionic.io.bundle.min.js` file isn't really feasible (not to mention modifying vendor code is considered bad practice)

Two possible solutions that spring to mind are:
* provide an API method for the config to be set in the config phase of the angular app
* allow config to be loaded from a global variable like `window.IO_CONFIG`

Thanks! :smile:

**Comment by ericb** [comment]
Absolutely @mattlewis92 , we have an open discussion already going in #41

**Comment by mattlewis92** [comment]
Oops, sorry I missed that! Glad to hear it's on the roadmap :smile:
