### ISSUE TITLE
Failed to find the bower component "ionic-platform-web-client".

### ISSUE THREAD

**Issue by Marleg** [driftyco/ionic-platform-web-client#75]
Hello,

Trying:
$ ionic add ionic-platform-web-client

Getting:
Failed to find the bower component "ionic-platform-web-client".
Are you sure it exists? (CLI v1.7.14)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 8
Node Version: v0.12.7

Then trying:
$ bower install --save-dev ionic-platform-web-client

And getting:
bower ionic#1.2.4               cached git://github.com/driftyco/ionic-bower.git#1.2.4
bower ionic#1.2.4             validate 1.2.4 against git://github.com/driftyco/ionic-bower.git#1.2.4
bower ionic-platform-web-client#*           cached git://github.com/driftyco/ionic-platform-web-client.git#0.6.0
bower ionic-platform-web-client#*         validate 0.6.0 against git://github.com/driftyco/ionic-platform-web-client.git#*
bower                                    ECONFLICT Unable to find suitable version for ionic-platform-web-client

Any ideas?

Thank you.

**Comment by ericb** [comment]
That's odd, it's definitely available. Perhaps try a `bower cache clean` or removing the platform client before adding it (assuming you had a previous version).

**Comment by Fuiste** [comment]
This is definitely an issue with bower and a bad error message from the Ionic CLI, rather than the platform web client.  We've updated the message in the latest CLI to be more descriptive, as simply assuming nonexistence was misleading.

To fix it, I'd suggest removing the platform web client completely, running `bower cache clean`, then reinstalling it with `ionic add` as @ericb said.  This should get you patched up.

**Comment by De-Lac** [comment]
same error, tried with bower cache clean, but I get the same error as before :(

**Comment by De-Lac** [comment]
Ok, it was a DNS problem!  Restoring the DNS to the default one, it works with

$ bower cache clean
$ ionic add ionic-platform-web-client

**Comment by Sundar-Ram** [comment]
Yes, after clearing the bower cache, it seems to work. Run the above 2 commands outside sudo mode.

**Comment by tebs85** [comment]
Bower error, check that "undefined" exists,
or try running "undefined" for more info. (CLI v2.0.0-beta.25)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.2 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by daggeto** [comment]
For me same thing after `bower cache clean`.
```
Bower error, check that "ionic-platform-web-client" exists,
or try running "bower install --save-dev ionic-platform-web-client" for more info. (CLI v1.7.15)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.4
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by DAKZH** [comment]
so? Did anyone fix this? ionic sucks I guess

**Comment by niallr12** [comment]
I am also experiencing this issue. 
Bower error, check that "undefined" exists,
or try running "undefined" for more info. (CLI v2.0.0-beta.25)

**Comment by DAKZH** [comment]
@niallr12 try to install with `bower install ionic-platform-web-client `

**Comment by DAKZH** [comment]
ionic really sucks. There changing everything they like, migrating to ReactNative

**Comment by niallr12** [comment]
In my case it was the inappbrowser causing the issue. I would like if the error message was more descriptive. Telling me "undefined" does not exist is not at all helpful.

**Comment by michaelonubogu** [comment]
Tried all solutions listed above and I'm still experiencing this issue.

**Comment by segrax** [comment]
Ensure you have git installed, and its available (type git and see if its working)

**Comment by dwieeb** [comment]
@segrax @michaelonubogu @niallr12 @DAKZH @daggeto @tebs85 

We seemed to have identified the issue. `bower.json` must exist prior to running the `ionic add` command. We are working on a fix now, but you can resolve the issue by running `bower init` and following the steps.

**Comment by nifft** [comment]
Same issue. I have git, bower cache is clean, DNS is working fine and I am stuck.
```
ionic add ionic-platform-web-client

Bower error, check that "ionic-platform-web-client" exists,
or try running "bower install --save-dev ionic-platform-web-client" for more info. (CLI v1.7.16)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.0.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v4.4.6

```

**Comment by dwieeb** [comment]
@nifft  `bower.json` must exist prior to running the `ionic add` command.

**Comment by nifft** [comment]
@dwieeb It exists. I have lots of bower components already.

**Comment by eduardoinnorway** [comment]
@dwieeb this issue is still a pain. I came to get this issue because we did try to add push with ionic.io to an an exciting app (so bower.json was there long time ago). Please put someone to look at this issue.

**Comment by dwieeb** [comment]
I've noticed the output from `bower install --save-dev ionic-platform-web-client` is 

```
bower ionic-platform-web-client#* cached git://github.com/driftyco/ionic-platform-web-client.git#0.6.0
bower ionic-platform-web-client#* validate 0.6.0 against git://github.com/driftyco/ionic-platform-web-client.git#*
```

See the `0.6.0`? That's not the current version (`0.7.1`): https://github.com/driftyco/ionic-platform-web-client/blob/master/bower.json

Somewhere (probably in bower cache) it's trying to install an older version. I don't know enough about the bower internals and we're moving away from bower very shortly so it's hard to dedicate someone to this issue, which ultimately I think is an issue with bower or how we're all using it. 

`ionic-platform-web-client` is being deprecated very, very soon. It is being replaced with the [Cloud Client](https://github.com/driftyco/ionic-cloud), which will be installed with npm.

- If you want to **start** using the Ionic Cloud and you're **good** at reading source code, install the client with `npm install --save @ionic/cloud`. You'll need to copy the library's dist file into `www/lib` and include it in your `index.html`. Then take a look at our [angular 1 integrations](https://github.com/driftyco/ionic-cloud/blob/master/src/angular.js). 
    - For Angular 2, start with this: https://github.com/driftyco/ionic-cloud-angular
- If you want to **start** using the Ionic Cloud and you're **not so good** at reading source code, it might be best to wait a little while for our brand new documentation.
- If you want to **migrate** your existing app to the new Cloud Client, read the [Migration Guide](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide).

Very soon, [our docs](http://docs.ionic.io) will be updated to reflect usage with the new Cloud Client.

**Comment by zeeshan-m** [comment]
I'd recommend updating https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower, http://docs.ionic.io/v2.0.0-beta/docs/io-install and http://docs.ionic.io/docs/analytics-from-scratch. Took me a while to google around and find this.

**Comment by zeeshan-m** [comment]
I'd recommend updating https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower, http://docs.ionic.io/v2.0.0-beta/docs/io-install and http://docs.ionic.io/docs/analytics-from-scratch. Took me a while to google around and find this. 

Do you have an ETA of when the analytics library will be released for the cloud client?

Is there anything we can do in the mean time if we want to use analytics or deployments?
