### ISSUE TITLE
Some iOS devices not receiving push notifications in background

### ISSUE THREAD

**Issue by jmanlapid** [driftyco/ionic-platform-web-client#76]
Hi, some iOS devices are not able to get push notifications in background mode. They will receive the notification that has already been sent out only if the app is surfaced in the foreground. Other devices are working fine. I'm using the latest version of cordova-plugin-push (1.6.0) and ionic-platform-web-client (0.6.0).

Here is my code which PushSrv.register() is called once the user logs in through our own authentication. The only reason I'm registering Ionic users is so that I can send notifications to all users in the Ionic.io dashboard.

```javascript
.factory('PushSrv', function($rootScope) {
  var user = {};
  var push = new Ionic.Push({
    debug: true,
    onNotification: function(notification) {
      console.log('notification received: ', JSON.stringify(notification));
    },
    pluginConfig: {
      ios: {
        alert: true,
        badge: true,
        sound: true
        //clearBadge: defaulted to false
      },
      android: {
        iconColor: "#343434"
      }
    }
  });
  return {
    register: function() {
      var details = {
        email: $rootScope.user.id + '@' + $rootScope.user.id + '.com',
        password: 'generic-password'
      };
      
      // sign them up, if error with code conlfict_email, then log them in, otherwise it goes straight to login
      Ionic.Auth.signup(details).then(ionicLogin, ionicFailure);

      function ionicLogin() {
        Ionic.Auth.login('basic', { remember: true }, details).then(registerPush, ionicFailure);
      }

      function ionicFailure(err) {
        if (err.errors[0] === 'conflict_email') {
          ionicLogin();
        }
      }

      function registerPush() {
        push.register(function(data) {
          // save the token in the ionic user
          push.saveToken(data.token);
          // update the ionic user object with current logged in parse user
          user = Ionic.User.current();
          user.details.name = $rootScope.user.get('firstName') + ' ' + $rootScope.user.get('lastName');      
          user.save();
        });
      }

    }
  };
```

**Comment by ericb** [comment]
There is no need to use Ionic.Auth if you just want to send to all. The dashboard will allow you to send to all (which uses device tokens). Tokens can be saved with or without a user.

This example also does not fully illustrate why some devices may not receive the notification when in the background.

**Comment by jmanlapid** [comment]
What information can I get you that would help debug this situation (XCode configurations, iOS device versions, console logs)?

**Comment by ericb** [comment]
Can you try installing a previous push-plugin version like 1.5.2

**Comment by Fuiste** [comment]
Depending on how you're sending notifications, this could be a result of the `priority` flag.  We've updated our API to default all notifications send through the dashboard to a priority of `10` ([docs](http://docs.ionic.io/docs/push-sending-push#section-setting-your-notification-s-priority))

Does changing the priority affect delivery?

**Comment by eugenedw** [comment]
I'm having a similar issue. After following guidance from the docs (http://docs.ionic.io/docs/push-sending-push), my iOS device never receives notifications - neither when the app is open or closed. The CURL request processes with no errors, so I can't understand what may be causing this. The only strange thing I noticed during initial setup was that the "ionic-platform-web-client" is never found:

eugene$ ionic add ionic-platform-web-client

Failed to find the bower component "ionic-platform-web-client".
Are you sure it exists? (CLI v2.0.0-beta.23)

Your system information:

Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.1
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175 

Did everything described here:
https://github.com/driftyco/ionic/issues/4468

No luck...

Push worked prior to migrating. Any ideas?

**Comment by ericb** [comment]
This happens when a dependency needs to be resolved by bower or there is an issue with permissions (or some other system level issue). You can see the direct cause by running bower install directly:

`bower install --save-dev ionic-platform-web-client`
