### ISSUE TITLE
$ionicPush.saveToken is undefined with update

### ISSUE THREAD

**Issue by Dosix** [driftyco/ionic-platform-web-client#77]
Hi,

Until the update for Ionic Push notificition, I got this error :

`Error in Success callbackId: PushNotification1095083716 : TypeError: $ionicPush.saveToken is not a function. (In '$ionicPush.saveToken(data.token)', '$ionicPush.saveToken' is undefined)`

 I follow instruction on ionic website but I seem it doesn't work :(

I use this code in my app 

```
$ionicPush.init({
        "debug": true,
        "onNotification": function (notification) {
          var payload = notification.payload;
          console.log(notification, payload);
        },
        "onRegister": function (data) {
          console.log(data.token);
          $ionicPush.saveToken(data.token);
        },
        "pluginConfig": {
          "ios": {
            "badge": true,
            "sound": true,
            "alert": true
          },
          "android": {
            "iconColor": "#343434"
          }
        }
      });

      $ionicPush.register();
```

Any idea how to register token device in ionic app ?

Thanks

**Comment by ericb** [comment]
If saveToken is undefined you'll need to update the install of this platform client. `ionic add ionic-platform-web-client` and then rebuild your config `ionic config build`

**Comment by walmon** [comment]
The configuration ericb put here didn't fix my problem, still have it
