### ISSUE TITLE
Device receives notification, but onNotification callback is only fired when app is in foreground

### ISSUE THREAD

**Issue by danielslz** [driftyco/ionic-platform-web-client#78]
So, what i did was:

1 - create a project:
`ionic start myPushApp tabs`

2 - Initialized ionic io:
`ionic io init`

3 - Setup GCM according to [this guide](http://docs.ionic.io/v2.0.0-beta/docs/android-push-profiles)

4 - Setup GCM key
`ionic config set gcm_key <my-gcm-project-number>`

5 - On Ionic.io dashboard, create the certificate and setup the GCM API Key

6 - Install ionic-platform-web-client
`ionic add ionic-platform-web-client`

7 - Install phonegap-plugin-push
`ionic plugin add phonegap-plugin-push --variable SENDER_ID="MY_GCM_PROJECT_NUMBER"`

8 - Set dev_push to false
`ionic config set dev_push false`

9 - Add push code inside run block in app.js
```
var push = new Ionic.Push({
  "debug": true,
  'onNotification': function (notification) {
    console.log(notification);
    alert('onNotification fired!');
  },
  'onRegister': function () {
    alert('onRegister fired!');
  }
});

push.register(function(token) {
  console.log("Device token:",token.token);
  push.saveToken(token);  // persist the token in the Ionic Platform
});
```
10 - Add Android platform
`ionic platform add android`

11 - Run app in a device
`ionic run`

12 - Send a push
```
curl -X POST -H "Authorization: Bearer MY_API_TOKEN" -H "Content-Type: application/json" -d '{
    "tokens": ["MY_DEVICE_TOKEN"],
    "profile": "test",
    "notification": {
        "message": "Hello World!"
    }
}' "https://api.ionic.io/push/notifications"
```

**Comment by ericb** [comment]
What happens if you send some data with the message:

```
curl -X POST -H "Authorization: Bearer MY_API_TOKEN" -H "Content-Type: application/json" -d '{
    "tokens": ["MY_DEVICE_TOKEN"],
    "profile": "test",
    "notification": {
        "message": "Hello World!",
        "android": {
            "data": {
                "somedata": "some test data"
            }
        }
    }
}' "https://api.ionic.io/push/notifications"
```

**Comment by danielslz** [comment]
Same behavior, onNotification not fired.

**Comment by danielslz** [comment]
Maybe [this help](http://github.com/phonegap/phonegap-plugin-push/issues/746).

**Comment by Fuiste** [comment]
@danielslz can you confirm that this is still happening with a fully updated platform web client?

We've updated some things on tha backend, and have gotten reports that the issue may be solved.

**Comment by Fuiste** [comment]
Update: After testing, we're marking this issue fixed as far as we can tell.

Let us know if it crops up again.

**Comment by danielslz** [comment]
It's ok now, work's fine, thank you guys!
