### ISSUE TITLE
How to import into ionic2 ?

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-platform-web-client#79]
How do I get started when there is no instructions on how to import? I don't know webpack yet and the documentation only shows a global Ionic.User / Ionic.Auth.

**Comment by sagivf** [comment]
![image](https://cloud.githubusercontent.com/assets/1857466/13976343/a501a49c-f0c7-11e5-9157-e73c4d548b60.png)
Just getting started and already errors... This is starting from scratch project...

**Comment by Fuiste** [comment]
The `ionic-platform-web-client` doesn't support Ionic 2 at the moment, but it's something we're actively working on.  We'll have full documentation available as soon as Ionic 2 support is in place.

**Comment by sagivf** [comment]
Thanks. A small message somewhere in the docs would be in place...
