### ISSUE TITLE
Ionic platform - Ionic.User feature

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic-platform-web-client#80]
Hi

Im trying to understand the use of the Ionic.User feature..
This feature means that i dont need to create/keep-track on the users im my own database? Or should I keep track both in ionic and in my own?

Are there any limitations? max numbers of users?

Thanks ahead

**Comment by Fuiste** [comment]
You can see our proposed usage limits for the Ionic Platform [here](http://ionic.io/pricing) (these are tentative) and an overview of the user service [here](http://docs.ionic.io/docs/user-overview)

As this isn't an issue or bug with the `ionic-platform-web-client`, I'm closing this issue, but feel free to ask questions regarding the platform and its features in our [Gitter channel](https://gitter.im/driftyco/ionic-io-testers) or at help@ionic.io
