### ISSUE TITLE
Error: ENOENT: no such file or directory, open './www/js/app.js'

### ISSUE THREAD

**Issue by warner-pinz** [driftyco/ionic-platform-web-client#81]
I got an error when executing:

> $ ionic add ionic-platform-web-client
WARN: ionic.config.js has been deprecated, you can remove it. 
Bower component installed - ionic-platform-web-client
ERROR:  Error: ENOENT: no such file or directory, open './www/js/app.js'
    at Error (native)
Is your app declaration contained in 'app.js'?
Adding component to index.html
Saved dev_push, writing to ionic.io.bundle.min.js...

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by ericb** [comment]
It looks like you're likely trying to use this with an Ionic 2 project, which we do not officially support at the moment. We are currently working on this and it should be available in the next few weeks (if not sooner)

**Comment by rajeshwarpatlolla** [comment]
I too have the same issue. The folder structure is modified a bit. So there is no `www/js/app.js` now. But when i install the `ionic-platform-web-client` it is saying as shown in the image below.

![screen shot 2016-06-02 at 10 19 11 am](https://cloud.githubusercontent.com/assets/9896335/15734268/7b46a3d4-28ab-11e6-8106-0f044842dc95.png)

**Comment by Mathijs003** [comment]
So when you get this error, it seems that the components are added to the index.hmtl? So everything still works or?

**Comment by ladmerc** [comment]
Any update on this? Apparently, ionic upload doesn't work with custom file structure

**Comment by Fuiste** [comment]
Your best bet would be moving over to the new `ionic-cloud` repo, which is the future of the `ionic-platform-web-client` and where we've implemented a new configuration method which solves this issue.  

@dwieeb wrote a migration guide [here](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide)
