### ISSUE TITLE
No correct behaivor of modal

### ISSUE THREAD

**Issue by sebrojas14** [driftyco/ionic-platform-web-client#82]
The ion-autocomplete modal doesn't behaves like a normal modal and than gives me problems. For example, I can´t show a Ionic confirmation modal with the ion-autocomplete showing (appears behind the ion-autocomplete)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. As this is an issue related to the framework and not the Ionic platform I will be moving this issue to the correct repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic#5962

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic#5963

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic#5964

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic#5965

**Comment by sebrojas14** [comment]
Sorry sorry, I had both pages opened (this an the ion-autocomplete)
