### ISSUE TITLE
push notification icons on android 5+

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic-platform-web-client#83]
Push notification icons are not coming through on Android 5+. Everything worked fine for Push alpha, but failing in push beta. 

My push notification payload is very simple:
```
    post_data = json.dumps({
        "tokens": [str(pushToken)],
        "profile": profile,
        "notification": {
            "ios": {
              "message": "Hello iOS!",
              "badge": 3,
            },
            "android": {
              "message": "Hello Android!",
            }
        }
    })

```

And here is my pluginConfig:
```
"pluginConfig": {
        "ios": {
          "badge": true,
          "sound": true
         },
         "android": {
           "icon": "notification", // this comes from the android/res/drawable folder
           "iconColor": "#1A96A9"
         }
      } 

```

Potentially related to this plugin issue:
https://github.com/phonegap/phonegap-plugin-push/issues/747

**Comment by Fuiste** [comment]
What error is getting reported when you check the individual message statuses?

[Here's](http://docs.ionic.io/v2.0.0-beta/docs/push-sending-push#section-checking-the-status-of-a-push) an example of this.

**Comment by djangojack** [comment]
@Fuiste this was solved through changes on the ionic server.

**Comment by Fuiste** [comment]
Ah, whoops.  Seems I forgot about that
