### ISSUE TITLE
Push notification not working on Desktop as we on Mobile

### ISSUE THREAD

**Issue by pareshmutha** [driftyco/ionic-platform-web-client#85]
Hi ,
when i am pusing the message i getting below message

{"errors":[],"app_id":"ede2746d","android":{"failure_reason":"","success":false,"sent":0},"ios":{"failure_reason":"","success":false,"sent":0},"status":"Queued"}

not able receive notification on Desktop.

i have also done
ionic push --google-api-key 
ionic config set gcm_key

can any one help me .
Thanks in advance.

**Comment by ericb** [comment]
That response is from our legacy Alpha API. Please [migrate to the beta](http://docs.ionic.io/docs/migration-guide) and open a new issue in the event a similar issue occurs.
