### ISSUE TITLE
Unable to Register Push

### ISSUE THREAD

**Issue by limcheepei** [driftyco/ionic-platform-web-client#87]
Hi,
Previously (2 weeks ago), I was able to register Push and got a device token successfully.

Today, I create a new app, and repeat the same steps described in http://docs.ionic.io/docs/push-full-setup. However, the Push.register is unable to register the device token. I compared both projects and found that the phonegap-plugin-push version is different. 

Can anyone verify if the latest ionic-platform-web-client or phonegap-plugin-push have some problems?

**Comment by ericb** [comment]
There's no issue that we are aware of. You may want to remove and re-add the platform project and double check that you don't have multiple versions of the plugin installed (depending on when you originally setup the plugin it had a different name in regards to cordova).
