### ISSUE TITLE
Multiple push notification tokens per user/device?

### ISSUE THREAD

**Issue by domharrington** [driftyco/ionic-platform-web-client#88]
Is there anyway to detect if this user has already been registered for push notifications before?

I'm testing an app on device and every time i uninstall/reinstall i get assigned a new push token when i call `push.register()`. This results in multiple push notifications coming to the same device.

I would like to deregister the first somehow as it will never be used again? Is this possible?

I know that there is the `push.unregister()` api when you have a push notification instance, but i'm referring to the other, old tokens?

**Comment by Fuiste** [comment]
The tokens endpoint [here](http://docs.ionic.io/docs/api-push#tokens) will take a `user_id` parameter which can be used to list tokens registered to a given user ID.  There are also DELETE and PATCH endpoints to remove and invalidate tokens through the API, respectively.

**Comment by domharrington** [comment]
I will try to RTFM next time.

**Comment by Fuiste** [comment]
No worries, glad to help!

**Comment by domharrington** [comment]
If anyone wants a quicker way to clear out their ionic user device tokens, i've written a greasemonkey script which adds a "Delete" button next to each token on the /users/list page of https://apps.ionic.io.

https://gist.github.com/domharrington/d30771913655ad7950982dffdef765f9

![screen shot 2016-06-06 at 15 47 04](https://cloud.githubusercontent.com/assets/848223/15826208/9baec9fc-2bfe-11e6-94ba-f998d5f768e1.png)

This makes a request to the DELETE api documented here: http://docs.ionic.io/docs/api-push#tokens-delete
