### ISSUE TITLE
Undefined "init" function for notification push

### ISSUE THREAD

**Issue by Oviglo** [driftyco/ionic-platform-web-client#91]
Hello,
I try to set notification push bat I have an error when I set "dev_push" to false:

ionic.io.bundle.js:5844 Uncaught TypeError: Cannot read property 'init' of undefined

After config my Android account and set keys.

Thanks for your help.

Regards.

**Comment by ericb** [comment]
You need to install the push plugin (if you have already done this, you may need to remove and add the platform)

**Comment by Oviglo** [comment]
OK, I need help for this.
I have installed the push plugin ("ionic plugin add phonegap-plugin-push --variable SENDER_ID=123456" and "ionic io init") but I have the error again.

**Comment by ericb** [comment]
Have you tried removing and re-adding the platform? `ionic platform rm android` , `ionic platform add android` (you can switch android for ios)

**Comment by Oviglo** [comment]
Yes, but I have this error in local, do I have to test on device ?
This error is on register function (for get a token)

**Comment by ericb** [comment]
Yes, you need to test with a physical device when using Full Push.

**Comment by Oviglo** [comment]
Ah thank you, it work know :)

Regards.

**Comment by shannsoft** [comment]
Hi i have did everything but still its getting error
