### ISSUE TITLE
401 "Authorization header is missing" when calling push.unregister()

### ISSUE THREAD

**Issue by Maistho** [driftyco/ionic-platform-web-client#92]
Every time I call `$ionicPush.unregister()`, I get the following response:
```json
{
  "meta": {
    "version": "2.0.0-beta.0",
    "request_id": "2717bdb6-6d71-40ff-83fb-a2477bf37ec3",
    "status": 401
  },
  "error": {
    "link": null,
    "message": "Authorization header is missing.",
    "type": "Unauthorized"
  }
}
```

Using:
ionic#1.2.4
ionic-platform-web-client#0.7.1

**Comment by Maistho** [comment]
Seems like it's caused by calling `Ionic.Auth.logout` before unregister. Should I not be able to unregister a push token after signing out?

**Comment by florentsuc** [comment]
Hey,
I am facing the same problem. And I'm not using `Ionic Auth` but only Ionic Push.
Here is the response: 
`{"error": {"link": null, "type": "Unauthorized", "message": "Authorization header is missing."}, "meta": {"status": 401, "request_id": "bdb03e6a-4c1b-4898-bcca-d267a8b689d2", "version": "2.0.0-beta.0"}}`

**Comment by dwieeb** [comment]
This should be fixed in the next beta release of https://github.com/driftyco/ionic-cloud 👍 

Thank you!
