### ISSUE TITLE
avoid necessity of $rootScope.$apply in angular apps

### ISSUE THREAD

**Issue by gruppjo** [driftyco/ionic-platform-web-client#93]
Hello, as I mentioned over here: https://github.com/driftyco/ionic-platform-web-client/issues/41#issuecomment-211885249: I'm currently implementing **ionic-platform-web-client** support into [Generator-M-Ionic](https://github.com/mwaylabs/generator-m-ionic), which we'll release soon.

As a part of this I'm providing a simple example use-case with the Ionic User Service of which you can see a screenshot [here](https://github.com/mwaylabs/generator-m-ionic/blob/dev/docs/ecosystems/ionic_platform.md#test-the-ionic-platform-sample). During the development I noticed I need to call: `$rootScope.$apply()` when using `Ionic.Auth.signup` or `Ionic.Auth.login` in order to update the UI. See lines 10, 24, 30 of the [sample controller](https://github.com/mwaylabs/generator-m-ionic/blob/dev/generators/ionic-platform/templates/user-ctrl.js).

Is this how it is when using the **ionic-platform-web-client** or am I missing something or just using it wrong?

Any statement highly appreciated!

**Comment by dwieeb** [comment]
Likely due [to this](https://github.com/driftyco/ionic-cloud/issues/4). Change detection isn't happening on native promises. Closing to consolidate.
