### ISSUE TITLE
browser-request fails on HTTP 204

### ISSUE THREAD

**Issue by Maistho** [driftyco/ionic-platform-web-client#94]
It seems that you suffer from this exact issue: https://github.com/iriscouch/browser-request/issues/14
Since ionic servers return 204 when invalidating a push token.

Browser-request doesn't seem very active (no commits in 2 years), so it might be reasonable to replace or fork it?

**Comment by dwieeb** [comment]
I believe we can use `request/request` with an `https` shim and browserify (which we're using already). It is a much more popular library and should be better supported.

**Comment by dwieeb** [comment]
We're going to address this in this branch: https://github.com/driftyco/ionic-platform-web-client/tree/ionic2-support

**Comment by dwieeb** [comment]
`browser-request` has been replaced with `superagent` in the new Cloud Client: https://github.com/driftyco/ionic-cloud

Thank you, @Maistho!
