### ISSUE TITLE
GCM push.register() does not return and reports 'another registration is already in progress'

### ISSUE THREAD

**Issue by metalaureate** [driftyco/ionic-platform-web-client#98]
I'm setting up GCM push for the first time and testing on an old S4 and newer Nexus 6. APNS push works fine on iOS but when the same code to register the token is called (yada yada push.register(function (token) {...})) with the GCM setup (I have gone through the setup three times to make sure I did not miss anything), the callback does not return. If the call is made to register a second time within a few minutes, Ionic platform returns with the error "another registration is already in progress".

I've got to assume that it is something I haven't gotten right in the set up, but what could I try?

**Comment by zixia** [comment]
Which issue is this duplicated with?

**Comment by ssswagatss** [comment]
@ericb  Please share the link of the duplicate issue. Facing the same issue.
