### ISSUE TITLE
problem: cant install with ionic 1.3.0

### ISSUE THREAD

**Issue by emps** [driftyco/ionic-platform-web-client#99]
Failed to find the bower component "ionic-platform-web-client".
Are you sure it exists? (CLI v1.7.14)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v4.4.3

**Comment by Fuiste** [comment]
@emps this is caused when bower can't select the correct version or needs more input.

Try running

```
bower install --save ionic-platform-web-client
```

**Comment by emps** [comment]
i have my old project that i updated to 1.3.0 using ionic lib update
and i cant use now ionic add ionic-platform-web-client
but if i start new blank project so i can use that command...
by adding with bower i dont get problems but its not same as with ionic add 
cause there is files modifications that i need to make this module working with my app

**Comment by emps** [comment]
new blank project (1.3.0)

**Comment by Fuiste** [comment]
You can still install with bower, you're just going to need to inject `'ionic.service.core'` into your app.js and include the bundle in your index.

Then run `ionic config build` and you should be good to go.
